### PR TITLE
Update version to 0.6.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by mziccard**

### CODE REVIEW

**Comment by mziccard** [comment]
@garrettjonesgoogle I no longer have write access, can we merge this before we merge anything else? Please ignore the duplicate failure indicators by Travis/AppVeyor, that was actually my fault, PR [is building fine](https://travis-ci.org/GoogleCloudPlatform/google-cloud-java/builds/175935409)

**Comment by garrettjonesgoogle** [comment]
merged!

**Comment by mziccard** [comment]
@garrettjonesgoogle thank you :)

**Comment by garrettjonesgoogle** [comment]
No, thank you!

**Pull request merged**
