### PR TITLE
Nio

### PR DESCRIPTION
**Pull request by romlogic**
updated to java link, and general good to have edits.

### CODE REVIEW

**Comment by sduskis** [comment]
@romlogic, please revert the `v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionAudioOrBuilder.java` changes, since that class is auto-generated.

**Comment by sduskis** [comment]
Also, it looks like there is a conflict that needs to be resolved in ITGcsNio

**Comment by sduskis** [comment]
@romlogic, there aren't any files in the PR anymore.  Can this be closed?

**Comment by romlogic** [comment]
yes, please.

**Pull request closed without merging**
