### PR TITLE
Use HTTPS links and redirects for docs

### PR DESCRIPTION
**Pull request by tswast**
Replaces https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2200

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
cc @pongad because his PR https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2267 will conflict with this

**Comment by garrettjonesgoogle** [comment]
Could you sync & resolve conflicts?

**Comment by tswast** [comment]
Are those Travis failures something I should worry about? I'm having trouble parsing the build logs.

**Comment by garrettjonesgoogle** [comment]
Ignore the oraclejdk7 failure (I'm going to remove that shortly). Also ignore the appveyor/branch failure - that ran integration tests, and the failures are due to tests that have since been turned off in master. You're good to merge.

**Pull request merged**
