### PR TITLE
WIP compute engine samples

### PR DESCRIPTION
**Pull request by elisheva-qlogic**

### CODE REVIEW

**Comment by sduskis** [comment]
@googleapis/yoshi-admins, do you have any idea about who ought to review this?

**Comment by JustinBeckwith** [comment]
@djmailhot and @fhinkel are probably the best to take a look :)

**Comment by fhinkel** [comment]
Me? Did you mean @kolea2 ?

**Comment by JustinBeckwith** [comment]
Hah, added you because I know you had gone digging through the Compute Engine APIs as well.  From the Java perspective - yes, @kolea2

**Comment by andreamlin** [comment]
Is this the right repo to host this in? These examples refer to the apiary clients, not the client that exists in this repo in google-cloud-clients/google-cloud-compute.

**Comment by andreamlin** [comment]
FWIW, there already exists a google-cloud-examples/.../[ComputeExample.java](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/compute/v1/ComputeExample.java) for the Compute client in this repo.

**Comment by JustinBeckwith** [comment]
@kolea2 should we just close this out?

**Pull request closed without merging**
