### PR TITLE
Merge master to spanner-gapic-migration

### PR DESCRIPTION
**Pull request by yihanzhen**

### CODE REVIEW

**Comment by pongad** [comment]
This is failing due to a missing class. @hzyi-google Do you know what's going on?

**Comment by hzyi-google** [comment]
It seems that gax 1.26 and above is forcing api-common 1.6, while api-common 1.6 removed `ResourceNameType` and thus broke bigtable. Anything I can do to work around that?

**Comment by garrettjonesgoogle** [comment]
@andreamlin is working on that

**Comment by hzyi-google** [comment]
PTAL

**Comment by pongad** [comment]
LGTM

**Pull request merged**
