### PR TITLE
make pubsub high perf compile

### PR DESCRIPTION
**Pull request by pongad**
This commit merges master into the branch and makes it the branch compile.

`AckDeadlineRenewerTest` is still timing out. I'll get to that in a later commit.

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Looks like the tests are probably getting locked up somewhere.

**Comment by pongad** [comment]
@garrettjonesgoogle Yes, the test are locked up at the bug fixed by https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1473.

**Comment by garrettjonesgoogle** [comment]
If the tests pass, then LGTM

**Comment by pongad** [comment]
@garrettjonesgoogle AppVeyor seems to be timing out for some reason. I don't have a retry button though...

**Comment by pongad** [comment]
A rerun is passing at https://ci.appveyor.com/project/pongad/google-cloud-java-dujhn/build/1 .
I'll go ahead and merge this.

**Pull request merged**
