### PR TITLE
chore: restore google-cloud-examples

### PR DESCRIPTION
**Pull request by suztomo**
Restoring the directory https://github.com/googleapis/google-cloud-java/tree/main_202208/google-cloud-examples to the main branch.

### CODE REVIEW

**Comment by suztomo** [comment]
The check fails

```
+ for path in $(find . -mindepth 2 -maxdepth 2 -name pom.xml | sort --dictionary-order | xargs dirname)
+ module_name=google-cloud-examples
+ version_file=./google-cloud-examples/versions.txt
++ grep -E '^((google-.*|grafeas|gapic\-libraries)).*:[0-9]+\.[0-9]+\.[0-9]+.*:[0-9]+\.[0-9]+\.[0-9]+.*$' ./google-cloud-examples/versions.txt
grep: ./google-cloud-examples/versions.txt: No such file or directory
```

**Comment by meltsufin** [comment]
@suztomo If you rename `pom.xml` to `pom.xml.bak`, you shouldn't have to make any changes to `generation\`.

**Comment by suztomo** [comment]
I now think it’s better to remove the pom.xml altogether.

**Comment by meltsufin** [comment]
> I now think it’s better to remove the pom.xml altogether.

When these get migrated to `java-docs-samples`, they might want to use something from `pom.xml` to start running the tests again, but I'm not sure how much in it is useful.

**Comment by meltsufin** [comment]
It looks like `pom.xml` is still there.

**Review by ddixit14 — APPROVED** [review]

**Review by meltsufin — APPROVED** [review]

**Pull request merged**
