### PR TITLE
Expose static method to get default project ID

### LINKED ISSUE #1207: Google Cloud Dataflow/Apache Beam and gcloud-java-core
We have two external pull requests which add logic to support the active gcloud profile, and also to get the project from the service account which are already supported by gcloud-java-core.

Dataflow/Apache Beam would like to depend on gcloud-java-core for the project detection logic found here: https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-core/src/main/java/com/google/cloud/ServiceOptions.java?l=66

And also the auth credentials detection here: https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-core/src/main/java/com/google/cloud/ServiceOptions.java?l=237

Currently these are hidden away, is there a way for you to expose these concepts without needing to create a ServiceOptions subclass?

If not, how do you advise Dataflow/Apache Beam to integrate with gcloud-java-core?

Note, that Apache Beam would be interested in the python versions of that code, and in general this would be useful in the other language implementations as well.

### PR DESCRIPTION
**Pull request by mziccard**
This replaces #1241 and fixes #1207

### CODE REVIEW

**Comment by lukecwik** [comment]
Any progress?

**Comment by lukecwik** [comment]
@garrettjonesgoogle ping?

**Comment by garrettjonesgoogle** [comment]
I can take care of merging this. @lukecwik , I think @mziccard cc'd you to see if you had feedback - does it look good as is?

**Comment by lukecwik** [comment]
I had reviewed #1241 previously which was a precursor to this. Those comments that were relevant to this change were already fixed so this looks good to me.

**Pull request merged**
