### PR TITLE
Add support for customer-supplied encryption keys

### LINKED ISSUE #1037: Support customer-supplied encryption keys in Storage
Support for customer-supplied encryption keys was added in storage and we should support it as well.

How to use such keys is documented [here](https://cloud.google.com/storage/docs/encryption#customer-supplied). Fields added to a blob are documented [here](https://cloud.google.com/storage/docs/json_api/v1/objects#customerEncryption).

### PR DESCRIPTION
**Pull request by mziccard**
This fixes #1037

### CODE REVIEW

**Comment by mziccard** [comment]
/cc @lesv 

(I'll add some more tests to avoid this coverage drop)

**Comment by lesv** [comment]
LGTM - Thanks for this!  Ping and I'll read the additional tests.

**Comment by mziccard** [comment]
@lesv I rebased on top of master and added more coverage.

**Comment by lesv** [comment]
LOL - coveralls says it decreased.

**Comment by lesv** [comment]
LGTM

**Pull request merged**
