### PR TITLE
fixing broken test - cloud/spanner/SessionPoolIntegrationTest.java

### PR DESCRIPTION
**Pull request by snehashah16**

### CODE REVIEW

**Comment by vkedia** [comment]
@vam-google Would you know why this test does not run on travis? That is why we never caught this issue. This is an integration test.

**Comment by snehashah16** [comment]
@vkedia - added some more java style, unused and other fixes.

**Comment by vkedia** [comment]
I see this error in appveyor build:
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/projects/google-cloud-java-v0gf7/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java:[38,6] cannot find symbol
  symbol:   class Parameter
  location: class com.google.cloud.spanner.SessionPoolOptionsTest
[ERROR] /C:/projects/google-cloud-java-v0gf7/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java:[40,6] cannot find symbol
  symbol:   class Parameter
  location: class com.google.cloud.spanner.SessionPoolOptionsTest
[ERROR] /C:/projects/google-cloud-java-v0gf7/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java:[38,6] cannot find symbol
  symbol:   class Parameter
  location: class com.google.cloud.spanner.SessionPoolOptionsTest
[ERROR] /C:/projects/google-cloud-java-v0gf7/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java:[40,6] cannot find symbol
  symbol:   class Parameter
  location: class com.google.cloud.spanner.SessionPoolOptionsTest
[INFO] 4 errors

**Comment by snehashah16** [comment]
@vkedia  - fixed missing import.

**Pull request merged**
