### PR TITLE
Add Encoder support to LoggingAppender

### PR DESCRIPTION
**Pull request by glindstedt**
This PR adds support to define a layout pattern for the loglines as described [here](https://logback.qos.ch/manual/layouts.html#ClassicPatternLayout). This is useful for example if you want to include stacktraces in the log messages sent to stackdriver.

I chose to provide a default encoder which matches the current log output, in order to not break backwards compatibility with any existing configurations.

Note that I have not tested configuring the encoder through `logback.xml`, the project I have available to test with configures the appender manually.

### CODE REVIEW

**Comment by glindste** [comment]
Any chance of getting this reviewed?

**Comment by garrettjonesgoogle** [comment]
@jabubake would you mind taking a look? (Or nominating someone else?)

**Comment by bigunyak** [comment]
Hi guys,
Do you have any estimates on when this could be merged and released?
I just stumbled on this when tried to add thread name to be logged along with log messages.
Btw, the [Usage](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-contrib/google-cloud-logging-logback#usage) section is sort of misleading stating:
 > See Logback filters for information on filtering log output and encoders for information on formatting.

At the time when encoders are not supported...

**Comment by glindste** [comment]
#2765 which was merged a few days ago fixes my main use case for this PR. I won't resolve the conflicts unless it's actually going to get reviewed, so if general encoder support is not needed feel free to close this PR.

**Comment by sduskis** [comment]
@glindste, I'm going to close this PR due to staleness.  Please feel free to reopen, and resolve conflicts if this is still relevant.

**Comment by ZeeD** [comment]
Hi

**Pull request closed without merging**
