### PR TITLE
fix: revert reverting [Many APIs] Update WORKSPACE files for rules_gapic, gax_java, generator_java versions

### PR DESCRIPTION
**Pull request by suztomo**
Reverts googleapis/google-cloud-java#8337, which reverted https://github.com/googleapis/google-cloud-java/pull/8305. 8305 was merged without OwlBot Java Postprocessor (owl-bot-staging directory). We should merged the change after processing OwlBot Java PostProcessor.

The idea is that OwlBot Java PostProcessor should process the content of owl-bot-staging if we wait. No need to have OwlBot service to re-create the pull request.

### CODE REVIEW

**Comment by suztomo** [comment]
GitHub said OwlBot PostProcessor failed

Screen Shot 2022-09-09 at 2 24 05 PM

But the build is still running.

https://pantheon.corp.google.com/cloud-build/builds;region=global/ad6c4072-86dd-46af-985b-f2f65dbe27d5?project=repo-automation-bots&jsmode=O&mods=logs_tg_staging

**Comment by suztomo** [comment]
It died with 80 minutes timeout

Screen Shot 2022-09-09 at 4 12 36 PM


```
Step #8: e9828dff6efe: Pull complete
Step #8: Digest: sha256:f18997e574d4544becdcee35cef3f23ebef78d8e2e3a982306106313dea50aed
Step #8: Status: Downloaded newer image for gcr.io/cloud-devrel-public-resources/owlbot-cli:latest
Step #8: gcr.io/cloud-devrel-public-resources/owlbot-cli:latest
Step #8: git add -A .
TIMEOUT
ERROR: context deadline exceeded
```

It was very close.

**Comment by suztomo** [comment]
I ran owlbot-java manually:

```
docker run --rm -v $(pwd):/workspace -w /workspace --user $(id -u):$(id -g) gcr.io/cloud-devrel-public-resources/owlbot-java
```

**Comment by suztomo** [comment]
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project google-analytics-data: Compilation failure: Compilation failure: 
Error:  /home/runner/work/google-cloud-java/google-cloud-java/java-analytics-data/google-analytics-data/src/main/java/com/google/analytics/data/v1beta/stub/HttpJsonBetaAnalyticsDataStub.java:[92,35] method toBody in class com.google.api.gax.httpjson.ProtoRestSerializer<RequestT> cannot be applied to given types;
Error:    required: java.lang.String,com.google.protobuf.Message
Error:    found: java.lang.String,com.google.analytics.data.v1beta.RunReportRequest,boolean
Error:    reason: actual and formal argument lists differ in length
```

**Comment by suztomo** [comment]
Screen Shot 2022-09-16 at 12 35 56 PM

**Comment by suztomo** [comment]
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project proto-google-cloud-websecurityscanner-v1: Compilation failure: Compilation failure: 
Error:  /home/runner/work/google-cloud-java/google-cloud-java/java-websecurityscanner/proto-google-cloud-websecurityscanner-v1/src/main/java/com/google/cloud/websecurityscanner/v1/Xxe.java:[111,9] cannot find symbol
Error:    symbol:   variable internal_static_google_cloud_websecurityscanner_v1_Xxe_descriptor
Error:    location: class com.google.cloud.websecurityscanner.v1.FindingAddonProto
Error:  /home/runner/work/google-cloud-java/google-cloud-java/java-websecurityscanner/proto-google-cloud-websecurityscanner-v1/src/main/java/com/google/cloud/websecurityscanner/v1/Xxe.java:[118,9] cannot find symbol
Error:    symbol:   variable internal_static_google_cloud_websecurityscanner_v1_Xxe_fieldAccessorTable
Error:    location: class com.google.cloud.websecurityscanner.v1.FindingAddonProto
Error:  /home/runner/work/google-cloud-java/google-cloud-java/java-websecurityscanner/proto-google-cloud-websecurityscanner-v1/src/main/java/com/google/cloud/websecurityscanner/v1/Xxe.java:[533,11] cannot find symbol
Error:    symbol:   variable internal_static_google_cloud_websecurityscanner_v1_Xxe_descriptor
Error:    location: class com.google.cloud.websecurityscanner.v1.FindingAddonProto
Error:  /home/runner/work/google-cloud-java/google-cloud-java/java-websecurityscanner/proto-google-cloud-websecurityscanner-v1/src/main/java/com/google/cloud/websecurityscanner/v1/Xxe.java:[540,11] cannot find symbol
Error:    symbol:   variable internal_static_google_cloud_websecurityscanner_v1_Xxe_fieldAccessorTable
Error:    location: class com.google.cloud.websecurityscanner.v1.FindingAddonProto
Error:  /home/runner/work/google-cloud-java/google-cloud-java/java-websecurityscanner/proto-google-cloud-websecurityscanner-v1/src/main/java/com/google/cloud/websecurityscanner/v1/Xxe.java:[573,11] cannot find symbol
Error:    symbol:   variable internal_static_google_cloud_websecurityscanner_v1_Xxe_descriptor
Error:    location: class com.google.cloud.websecurityscanner.v1.FindingAddonProto
```

**Comment by suztomo** [comment]
All checks green.

**Review by meltsufin — APPROVED** [review]

**Pull request merged**
