### PR TITLE
Spanner: Min backoff should be 250ms

### LINKED ISSUE #5544: Spanner: Adjust timeouts for CreateDatabase and retries for other methods
As part of a recent change to GAPIC Configuration, timeouts and retries need to be updated. 

Ensure that the timeouts and retires specified in https://github.com/googleapis/googleapis/commit/cc233544aa39b8947c9b929819aeb08e2cb71feb#diff-4501db3e3507bcce8496c9aea2017d96 are reflected in this client library.

### PR DESCRIPTION
**Pull request by olavloite**
Fixes #5544

### CODE REVIEW

**Comment by kolea2** [comment]
Hmm.. I thought the 250 ms was picked up by this PR: https://github.com/googleapis/google-cloud-java/pull/5523. Is this still needed?

**Comment by olavloite** [comment]
The 250ms is picked up for all timeouts for normal gRPC calls. It is not automatically picked up for the custom retry logic in the Spanner library that is still used for:
* Retrying aborted transactions
* Retrying broken streaming result sets

**Comment by kolea2** [comment]
Apologies, just read through the issue. I think this should be picked up automatically and we shouldn't rely on hardcoded constants - let's go back to the issue and figure out where that should go to work as expected.

Separately, can we move the session not found commit to a new PR?

**Comment by olavloite** [comment]
I'll move the `SessionNotFound` issue into a separate PR. Closing this to continue the discussion in the original issue.

**Pull request closed without merging**
