### PR TITLE
use Method getters rather than deprecated static fields

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
cc: @vkedia

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
@pongad The dependent issue https://github.com/googleapis/gapic-generator/issues/1856  was recently closed as fixed, would it be possible to rerun the tests?

**Comment by pongad** [comment]
This is still failing. I'll figure out why as part of GCJ release this week.

**Comment by carl-mastrangelo** [comment]
@pongad did you get a chance to look into this?

**Comment by pongad** [comment]
Conflict because we moved the file. @carl-mastrangelo I opened a new PR for this. Let me know if it looks OK to you.

**Comment by pongad** [comment]
Superseded by #3299

**Pull request closed without merging**
