### PR TITLE
Syncing my fork (this CL has no changes).

### PR DESCRIPTION
**Pull request by aozarov**

### CODE REVIEW

**Comment by jgeewax** [comment]
Wait - if there are no changes, why not just ...

```
$ git pull upstream master  # Where upstream is GoogleCloudPlatform/gcloud-java
$ git push origin -f  # Where origin is aozarov/gcloud-java
```

?

**Comment by aozarov** [comment]
Yes, please ignore this pull request (I will delete it soon), this is why I didn't assign it to anyone.
It is one of my many attempts to recover my fork from #11

**Comment by aozarov** [comment]
BTW, when I am invoking
$ git pull upstream master  # Where upstream is GoogleCloudPlatform/gcloud-java 
I get several conflicts:
Auto-merging src/test/java/com/google/gcloud/storage/SerializationTest.java
CONFLICT (add/add): Merge conflict in src/test/java/com/google/gcloud/storage/SerializationTest.java
Auto-merging src/test/java/com/google/gcloud/storage/ListResultTest.java
...
Automatic merge failed; fix conflicts and then commit the result.

Any idea on how to handle those (and basically force taking the upsteam)?

**Comment by jgeewax** [comment]
Seems like this answer makes sense here: http://stackoverflow.com/questions/8134960/how-to-revert-master-branch-to-upstream

**Pull request closed without merging**
