### PR TITLE
Add new Cloud Tasks version

### PR DESCRIPTION
**Pull request by danoscarmike**
Add Cloud Tasks v2beta3 to batch generation
Update path to Cloud Tasks v2beta2 artman config (file renamed)

### CODE REVIEW

**Comment by pongad** [comment]
@andreamlin Could you look into this as part of regenerating this week?

**Comment by andreamlin** [comment]
v2beta3 has already been added to google-cloud-java, see https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta3.

**Comment by andreamlin** [comment]
I believe these changes are already in master: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/utilities/batch_generate_apis.py

**Comment by andreamlin** [comment]
@danoscarmike Can you confirm that the changes are already in master (see previous comments), and close this PR if so, or explain what else needs to be done for adding v2beta3 of cloud-tasks?

**Comment by danoscarmike** [comment]
Yep, looks good. I'll close this now. Thanks @andreamlin!

**Pull request closed without merging**
