### PR TITLE
Datastore: fix NullPointerException in TransactionExceptionHandler (#2256)

### PR DESCRIPTION
**Pull request by cmaan**
fix NullPointerException caused by user exceptions nested in datastore transactions (#2256)

### CODE REVIEW

**Comment by cmaan** [comment]
I signed it!

**Comment by cmaan** [comment]
@garrettjonesgoogle I'm not sure why @googlebot complains, I got an organizational CLA signed before opening the pull request, the email address should be the same for all of commit, github, as well as google group - anything else I could be missing?

**Comment by garrettjonesgoogle** [comment]
Hmm, try adding additional e-mails to your github account that you might have possibly used somewhere in the process.

**Comment by cmaan** [comment]
I signed it!

**Comment by cmaan** [comment]
I signed it!

**Comment by cmaan** [comment]
I signed it!

**Comment by cmaan** [comment]
I signed it!

**Comment by cmaan** [comment]
I signed it!

**Comment by cmaan** [comment]
I signed it!

**Pull request merged**
