### PR TITLE
chore(bazel): [java-datacatalog] Update WORKSPACE files for rules_gapic, gax_java, generator_java versions

### PR DESCRIPTION
**Pull request by lqiu96**
This is to resolve a diff that was discovered in https://github.com/googleapis/google-cloud-java/pull/8448

### CODE REVIEW

**Comment by suztomo** [comment]
https://github.com/googleapis/java-datacatalog/pull/795 was merged on May. This monorepo started late August. That PR 794 cannot be the cause of diff.

**Comment by lqiu96** [comment]
> [googleapis/java-datacatalog#795](https://github.com/googleapis/java-datacatalog/pull/795) was merged on May. This monorepo started late August. That PR 794 cannot be the cause of diff.

I don't think the diff was because of [googleapis/java-datacatalog#795](https://github.com/googleapis/java-datacatalog/pull/795) -- It looks like the changes in java-datacatalog#795 was reverted

PR 8340 reverted the changes that went in [googleapis/java-datacatalog#795](https://github.com/googleapis/java-datacatalog/pull/795): https://github.com/googleapis/google-cloud-java/pull/8340/files#diff-ebe3de62a47cce7750d33539cd0fec2f5169fe3d14c490b48bdd9c14a08a1b98

**Comment by suztomo** [comment]
@lqiu96 The java-datacatalog repository hasn't merged https://github.com/googleapis/java-datacatalog/pull/857 (open).

**Comment by lqiu96** [comment]
I see. Ok, I'll leave java-datacatalog files as a known difference then. We'll have to wait for the person on support to merge that PR.

**Comment by suztomo** [comment]
I just merged https://github.com/googleapis/java-datacatalog/pull/857

**Pull request closed without merging**
