### PR TITLE
Stackdriver product rename

### PR DESCRIPTION
**Pull request by tmatsuo**
Renaming some APIs to Stackdriver brand

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Change this here instead: https://github.com/googleapis/googleapis/blob/master/google/logging/logging.yaml#L6

**Comment by mziccard** [comment]
@garrettjonesgoogle Can I merge this or should we wait next code generation?

**Comment by garrettjonesgoogle** [comment]
Hmm I would at least like an open PR with the same change filed against googleapis :-)

**Comment by tmatsuo** [comment]
This PR is generated by an automated script (so there are bunch of similar PRs among GCP org). I should have used a bot, rather than my account.

Anyways, I'd appreciate it if @garrettjonesgoogle takes care of changes in other repo :)

Sometimes I run an automated script which grep and replace strings like this. Do you want me to blacklist this repo, or is a PR like this still a good reminder so that I can continue creating such PRs?

**Comment by garrettjonesgoogle** [comment]
PR created: https://github.com/googleapis/googleapis/pull/127

@tmatsuo why not include the googleapis repo in your automated script?

**Comment by tmatsuo** [comment]
@garrettjonesgoogle Yeah probably it makes sense to include googleapis org too. I will try next time.

**Comment by garrettjonesgoogle** [comment]
FYI there is both an org https://github.com/googleapis and a repo https://github.com/googleapis/googleapis under that org.

**Comment by mziccard** [comment]
> Sometimes I run an automated script which grep and replace strings like this. Do you want me to blacklist this repo, or is a PR like this still a good reminder so that I can continue creating such PRs?

Please keep firing these PRs whenever you find something odd :)

**Pull request merged**
