### PR TITLE
Remove usage of shaded netty in imports in favor of none shaded one

### PR DESCRIPTION
**Pull request by mbril**
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for context and/or discussion)

### CODE REVIEW

**Comment by chingor13** [comment]
@garrettjonesgoogle I'm not sure the history on why we use grpc-netty-shaded, but I presume it's because of diamond dependencies issues with netty major versions?

**Comment by garrettjonesgoogle** [comment]
Netty doesn't follow semantic versioning; they break compatibility between minor versions. Netty was the cause of some of our worse early diamond dependency conflicts. I think it is unwise to switch off of grpc-netty-shaded. cc @ejona86

**Comment by mbril** [comment]
Abandoning the PR, due to issues with non shaded netty in the past

**Comment by ejona86** [comment]
Yes, grpc-java recommends using grpc-netty-shaded for most users, as is visible [in our public documentation](https://github.com/grpc/grpc-java/blob/master/README.md). gRPC uses unstable APIs in Netty and even if that weren't the case Netty itself does not follow semantic versioning (4.1 was allowed to break interfaces in 4.0). But also depending on the correct netty-tcnative version can be a bit hard for users, and grpc-netty-shaded includes the correct netty-tcnative version.

**Pull request closed without merging**
