### PR TITLE
Remove RemoteGcsHelper.create(String, String) and other minor fixes

### PR DESCRIPTION
**Pull request by mziccard**
This PR does the following:
- Remove `RemoteGcsHelper.create(String, String)` (2808d95)
- Fix storage example in `testing/package-info.java` (2808d95)
- Fix functional classes tests (2808d95)
- Change storage code to make checkstyle happy (6edd748)

### CODE REVIEW

**Comment by aozarov** [comment]
Looks good to me. @ajkannan good finding. Some more cleanup items (could be done in a separate PR):

* BlobInfo#580 - Inefficient keySet iterator (Use entrySet).
* Storage interface has redundant "public static final" modifiers for DEFAULT_CONTENT_TYPE.
* BlobInfo.Builder#metadata is missing generic type on the right side.
* ITStorageTest is missing generic type for metadata in testListBlobsSelectedFields and testListBlobsSelectedFields
* StorageRpc.write - we don't use the dest param (I think was added for version check, but not used because the feature is missing in the JSON API). Should we
remove it (or add a comment suggesting why we have it)?
*  Bucket.BlobPageFetcher#nextPage, right side assignment could use the diamond shortcut
* BlobTest.testLoadFromId - should we add assertNotNull(loadedBlob) before using it? (Same comment for BucketTest.testLoad).
* StorageImplTest - multiple cases of redundant generic type declaration when
  using captured options - > assignment could use Capture.newInstance()

* Spelling issues:
Acl.java - 'Creats' 
BlobTest - 'delele'
DefaultStorageRpc - 'Reponse'



BTW, I keep seeing this message for the maven (applies to all modules):
"Definition of groupId is redundant, because it's inherited from the parent "

**Comment by mziccard** [comment]
@ajkannan I fixed your comments in place
@aozarov I added efb1ae6 to fix your comments

I will look into maven's complaint!

**Comment by aozarov** [comment]
I think you missed this one:
"ITStorageTest is missing generic type for metadata in testListBlobsSelectedFields and testListBlobsSelectedFields"

**Comment by mziccard** [comment]
Changed to assert and fixed missing comments in place

**Comment by aozarov** [comment]
> I will look into maven's complaint!

Hey @mziccard did you have a chance to look at that, "Definition of groupId is redundant", complaint?

**Comment by mziccard** [comment]
Actually I forgot :) I'll look into this.

**Pull request merged**
