### PR TITLE
Bump gax to 1.42.0

### PR DESCRIPTION
**Pull request by andreamlin**

### CODE REVIEW

**Comment by sduskis** [comment]
As per the comment, please update `google-cloud-bom/pom.xml`'s version of gax.

**Comment by andreamlin** [comment]
Looks like there might need to be a little tinkering to get things to match up right. I'll get on that.

**Comment by andreamlin** [comment]
Regenerated the compute client with the latest artman + gapic-generator to match the new gax interfaces.

**Comment by sduskis** [comment]
Awesome!

@elisheva-qlogic, your changes to the GAPIC generator made it into this PR.

**Pull request merged**
