### PR TITLE
Change deprecated kind(String) method to setKind(String) in README.MD

### PR DESCRIPTION
**Pull request by pauloleitemoreira**

### CODE REVIEW

**Comment by pauloleitemoreira** [comment]
I signed it!

Em 24/11/2016 15:49, "googlebot" <notifications@github.com> escreveu:

**Comment by lesv** [comment]
@garrettjonesgoogle AppVeyor failed on DNS for this, succeeded for Travis, I'm going to approve this.

```
Tests run: 35, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.391 sec <<< FAILURE! - in com.google.cloud.dns.testing.LocalDnsHelperTest
testListRecordSets(com.google.cloud.dns.testing.LocalDnsHelperTest)  Time elapsed: 0.032 sec  <<< FAILURE!
java.lang.AssertionError
	at com.google.cloud.dns.testing.LocalDnsHelperTest.testListRecordSets(LocalDnsHelperTest.java:822)

    assertNull(record.getType());
    assertNotNull(record.getTtl());
    assertNull(listResult.pageToken());
```

Appears to be `getTtl()` being Null.

**Comment by lesv** [comment]
Thank you for your submission.

**Comment by garrettjonesgoogle** [comment]
@lesv AppVeyor seems to be failing on that test for every PR.

**Pull request merged**
