### PR TITLE
Adding a dnsName filter option for Zone listing and removes nameServerSet exposure

### LINKED ISSUE #630: Remove acessors to nameServerSet when creating a managed zone
Most users do not need this.

### PR DESCRIPTION
**Pull request by mderka**
Only minor fixes. Fixes #630 and #602.

### CODE REVIEW

**Comment by mderka** [comment]
Also adds serialization test and fixes #631.

**Comment by mziccard** [comment]
If nobody started reviewing yet, could you rebase the commits and get rid of 53ee283?

**Comment by mderka** [comment]
Done.

**Comment by aozarov** [comment]
Looks good to me. Just need to add `DnsRecord` and `ChangeRequest` to the serialization tests.

**Comment by mderka** [comment]
Done. Squashed.

**Pull request merged**
