### PR TITLE
Generation support

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
- NIO read channel checks on reopen that the generation didn't change
- Fake (in-memory) storage has basic support for generations

This PR makes the NIO code more robust (it'll detect modifications to files while they're being read), and makes the fake storage (`FakeStorageRPC`) useful for testing a larger number of scenarios.

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
@jean-philippe-martin , do you have someone on your own team that is familiar with the NIO implementation that can review your changes on an ongoing basis? I think that would help with your agility, and reviewers in your space might be able to dive more deeply than us. Our team can still sanity check before merging.

**Comment by jean-philippe-martin** [comment]
@garrettjonesgoogle unfortunately no one in my team is familiar with NIO. I'll see if I can find someone else to help.

**Comment by garrettjonesgoogle** [comment]
@jean-philippe-martin it looks like conflicts need to be resolved before this can be merged.

**Comment by jean-philippe-martin** [comment]
This version should resolve the conflict; let's check that the tests still pass.

**Comment by garrettjonesgoogle** [comment]
LGTM - I'll merge after tests run

**Comment by jean-philippe-martin** [comment]
Excellent, thank you very much @garrettjonesgoogle ! And happy new year!

**Comment by jean-philippe-martin** [comment]
The tests failed. I see failures in `com.google.cloud.logging.v2.ConfigClientTest`, `com.google.cloud.datastore.DatastoreTest`, and `com.google.cloud.pubsub.v1.SubscriberTest`. They seem unrelated to the change. Is it possible these tests might report false positives?

**Comment by garrettjonesgoogle** [comment]
The Travis tests passed. That's good enough for me.

**Comment by jean-philippe-martin** [comment]
Great, thank you!

**Pull request merged**
