### PR TITLE
Add linter presubmit test

### PR DESCRIPTION
**Pull request by chingor13**
This adds a Kokoro test job "Kokoro - Test: Code Format" that runs all code outside of google-api-grpc through the google-java-format code linter via the `com.coveo:fmt-maven-plugin`.

We also fix all the code style issues.

### CODE REVIEW

**Comment by chingor13** [comment]
We will likely want to update all the code after we merge the PRs that we plan on releasing this week. Other PRs can fix any potential merge conflicts.

**Comment by sduskis** [comment]
@chingor13 which files did you change manually for this PR?

**Comment by chingor13** [comment]
@sduskis Only the code in the first 3 commits: https://github.com/googleapis/google-cloud-java/compare/master...e636610

The final commit was from running the fixer command: `mvn com.coveo:fmt-maven-plugin:format `

**Comment by chingor13** [comment]
Looks like I need to add an exception for the generated code in google-cloud-clients. Otherwise, autosynth PRs will fail the linter checks.

**Comment by chingor13** [comment]
Adding the ability to reformat the generated java code in: https://github.com/googleapis/synthtool/pull/145. Will open a new PR with those changes.

**Pull request closed without merging**
