### PR TITLE
Upgrade gax and guava dependencies

### LINKED ISSUE #3931: Upgrade Guava to the latest version
[Spring Cloud GCP](https://github.com/spring-cloud/spring-cloud-gcp) uses `google-cloud-bom` for the common dependencies. We have recently turned on Snyk vulnerability detection, and it found a [deserialization issue](https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236) with Guava 20.0. 
The recommended remediation step is to upgrade to 24.1.1 or higher.

Would it be possible to upgrade Guava version in [google-cloud-clients POM](https://github.com/googleapis/google-cloud-java/blob/a7bd8a5717e70d7df2ee8e57ed1a37dac0bde94e/google-cloud-clients/pom.xml#L163)?

Spring Cloud GCP tracking issue: spring-cloud/spring-cloud-gcp#1207

### PR DESCRIPTION
**Pull request by chingor13**
Fixes #3931 
gax version to 1.35.0 and guava to 26.0-android

### CODE REVIEW

**Comment by andreamlin** [comment]
Oh no, is this is a diamond dependency issue? Looks like the newest versions of our dependencies each use different versions for org.codehaus.mojo:animal-sniffer-annotations (1.14 and 1.17)

**Comment by chingor13** [comment]
Bleh, animal-sniffer-annotations dependency versions don't converge between guava 26.0-android, and grpc even though grpc uses guava 26.0-android.

I can add a temporary lock on the animal-sniffer-annotations version. It's ok because the versions should be compatible (not a semver major version difference).

**Comment by stevenschlansker** [comment]
This PR seems to introduce numerous problems in projects that use `26.0-jre`.  Was there a particular reason to pick the android build?  We're hitting dependency convergence errors:

```
[INFO] --- maven-dependency-versions-check-plugin:2.0.2:check (default) @ mycorp-server ---
[INFO] Checking dependency versions
[ERROR] Found a problem with the direct dependency com.google.guava:guava of the current project
  Expected version is 26.0-jre
  Resolved version is 26.0-jre
  Version 26.0-android was expected by artifact: com.google.cloud:google-cloud-logging-logback
  Version 26.0-jre was expected by artifacts: com.mycorp.components:mycorp-jaxrs-client, com.mycorp.components:mycorp-spring
```

**Comment by andreamlin** [comment]
We chose the android flavor because it supports JDK 7. (See guava [README](https://github.com/google/guava)).

**Comment by stevenschlansker** [comment]
OK.  Unfortunately, it conflicts with the `-jre` version; I opened an issue #4440

**Comment by sduskis** [comment]
Let's please continue the discussion on the issue.

**Pull request merged**
