### PR TITLE
Update tar to include json file

### PR DESCRIPTION
**Pull request by ajkannan**
This PR deals with the necessary `travis`-branch updates mentioned in #214.  Namely, the signing tools and json file are now combined in a single encrypted zipped file.

### CODE REVIEW

**Comment by ajkannan** [comment]
(This PR will be followed by a PR in the master branch to update the file decryption command)

**Comment by ajkannan** [comment]
Update: interestingly enough, the key originally created for the signing-tools.tar was overwritten, meaning no additional PR is necessary in the master branch to update the signing process.

**Comment by mziccard** [comment]
@ajkannan In fact I was looking for new decryption keys in the travis config without success. That's surprising. If you confirm that the variables got updated I think we can merge!

**Comment by ajkannan** [comment]
The output from the file encryption says that the secure environment variables were indeed stored, and I just tried a similar key update on my personal repo, and it looks like the keys were overwritten, just like what happened here.  So I believe the variables did update, but I'm unsure of a better way to explicitly check.

**Pull request merged**
