### PR TITLE
Add codacy badge and configuration

### PR DESCRIPTION
**Pull request by mziccard**
As per title this PR adds codacy badge to project's READMEs and also adda codacy configuration to the root of the project (named `codacy-conf.json`).

`codacy-conf.json` is not exactly human readable but can be imported and exported in codacy where you can edit it and export again (and possibly push to this repository).

I already did a pass disabling checks that we don't need and enabling the ones that I believe we should enforce. We could also consider disabling all checks related to CSS and Javascript.

### CODE REVIEW

**Comment by aozarov** [comment]
BTW, did you understand how to include coverage data with codacy?
We don't really need it as Coveralls should be enough, but if trivial it would be nice.

**Comment by aozarov** [comment]
This PR relates to #626

**Comment by mziccard** [comment]
I did't look into it as we already have coveralls. Is it worth having two services checking for coverage? Or do you want to assess whether codacy's report is more accurate that Coveralls?

Also as you've seen by yourself codacy can be slow in providing the report to a PR, while coveralls shows the report almost in real time.

**Comment by aozarov** [comment]
Right, it is not important. I was only curious as when you go to the codacy main page for the project you see it mentioned as "not configured". Also, I was curious to see if their report is more helpful in showing the missing coverage"...

**Comment by mziccard** [comment]
I've been in touch with codacy's support today and they told me that the latency we are experiencing in seeing codacy's status after our PRs should be fixed soon. As soon as it becomes more responsive we can give it a try!

**Comment by aozarov** [comment]
Sounds Good!

**Pull request merged**
