### PR TITLE
Firestore: Add @Deprecated annotation to getCollections

### PR DESCRIPTION
**Pull request by schmidt-sebastian**
These methods are deprecated as per the JavaDoc but we should probably use an Annotation as well.

### CODE REVIEW

**Comment by BenWhitehead** [comment]
I'm okay with the additional detail, but the javadocs don't seem to provide an alternative of how the users is supposed to be able to do this sort of operation. Do you know what the replacement is that we could refer to?

**Comment by schmidt-sebastian** [comment]
The JavaDoc's deprecated comments do say to use `listCollections()`. GitHub decided that is not worth showing :/ Is there something else we should be doing?

**Comment by BenWhitehead** [comment]
Ah, so it does my mistake. LGTM.

**Comment by BenWhitehead** [comment]
Actually, can we change the deprecation javadocs to use this format:
```
   * @deprecated Use {@link #listCollections()}.
```

Instead of the back-ticks. This will make the link clickable in the javadocs if we do it.

**Comment by schmidt-sebastian** [comment]
Updated the JavaDoc to use the links as suggested.

**Pull request merged**
