### PR TITLE
chore: use `CLOUD_JAVA_BOT_TOKEN` in generate_new_client.yaml

### PR DESCRIPTION
**Pull request by diegomarquezp**
Some actions are failing in commands that require github authentication
https://github.com/googleapis/google-cloud-java/pull/10179#issuecomment-1896546716

This includes `generate_new_client.yaml`. In this PR I try the Cloud Java Bot Github token to check whether this is a token expiration problem

Edit: see one of the resulting PRs: https://github.com/googleapis/google-cloud-java/pull/10238

### CODE REVIEW

**Comment by diegomarquezp** [comment]
Currently investigating:

```
+ gh pr create --fill --head new-library/meet-qwvU5
could not compute title or body defaults: failed to run git: fatal: ambiguous argument 'origin/main...new-library/meet-qwvU5': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

From https://github.com/googleapis/google-cloud-java/actions/runs/7561708004/job/20590583313

**Comment by suztomo** [comment]
It seems the problem is "--fill" option https://github.com/cli/cli/issues/5896. If you explicitly specify title and body, it may work.

**Comment by diegomarquezp** [comment]
```
gh pr create --title 'feat: [meet] new module for meet' --body 'Generated with https://github.com/googleapis/google-cloud-java/actions/workflows/generate_new_client.yaml

Command used:

```
python generation/new_client/new-client.py generate --api_shortname="meet" --proto-path="google/apps/meet" --name-pretty="Google Meet API" --product-docs="https://developers.google.com/meet/api/guides/overview" --api-description="The Google Meet REST API lets you create and manage meetings for Google Meet and offers entry points to your users directly from your app" --transport="grpc"
```' --head new-library/meet-jcOi0
pull request create failed: GraphQL: must be a collaborator (createPullRequest)
```

I thought Cloud Java Bot was a collaborator, I'll check on that. We can always use `${{ github.token }}` though

**Comment by diegomarquezp** [comment]
https://github.com/googleapis/google-cloud-java/pull/10238 was the latest run - looks OK

**Review by suztomo — APPROVED** [review]

**Review by suztomo — APPROVED** [review]

**Pull request merged**
