### PR TITLE
Update links to google-cloud-node and google-cloud-php landing pages

### PR DESCRIPTION
**Pull request by mziccard**

### CODE REVIEW

**Comment by lesv** [comment]
LGTM - be prepared at some point they will rename us as well.

**Comment by mziccard** [comment]
> be prepared at some point they will rename us as well.

I plan to do that by the end of the week :)

**Comment by lesv** [comment]
So what they found on Node is that there will be broken links everywhere that don't get referrals.  We will also need to update docs on c.g.c & d.g.c once this happens.

**Pull request merged**
