### PR TITLE
Fix requester pays issues: #2392, #2391 and #2439.

### PR DESCRIPTION
**Pull request by vam-google**
Fixes for #2392, #2391 and #2439

To get requesterPays info on a bucket:
```java
Bucket bucket = storage.get(bucketName, Storage.BucketGetOption.fields(BucketField.BILLING));
```

To download a bucket 
```java
blob.downloadTo(destFilePath, Blob.BlobSourceOption.userProject(projectId));
```
or directly use `Blob.reader(BlobSourceOption... options)` method.

### CODE REVIEW

**Comment by jabubake** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java#L696 seems wrong
Also, given this change, can you update
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/82fa63d01fe19b5158f258f2a2991378e074ab0f/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java#L1507
to use the `BILLING` field and assert that `requesterPays` is `false`.

**Comment by vam-google** [comment]
Fixed the `BucketTest`, left `ITStorageTest` untouched as we discussed. 
Note, `requesterPays()` will still return null if it is set to null on server (i.e. even if we request a bucket with `BucketField.BILLING` option specified, but on server it is set to null, the client will return `null`, not `false`) . In such cases it is essentially has same meaning `false`, but client still returns null to stay consistent and provide accurate information about data returned from server.

**Comment by vam-google** [comment]
PTAL

**Comment by jabubake** [comment]
LGTM

**Comment by frankyn** [comment]
Thanks for picking this up! +1 LGTM.

**Pull request merged**
