### PR TITLE
chore: Introducing release profile for non-cloud clients.

### PR DESCRIPTION
**Pull request by ddixit14**

### CODE REVIEW

**Review by suztomo — APPROVED** [review]
Merge once the artifacts appear in Maven Central.

**Comment by suztomo** [comment]
The artifacts are available in Maven Central. Example: https://central.sonatype.com/artifact/com.google.maps/google-maps-mapsplatformdatasets/0.1.0

**Comment by meltsufin** [comment]
> 🥚 You hatched a release! The release build finished successfully! 💜

What going on in this PR? It's not a release PR.
Also, I would suggest changing the PR title because the profile is not just for maps, but for all non-cloud clients.

**Comment by ddixit14** [comment]
This PR was raised to trigger the release for non-cloud clients. The release went through, but we had a required [test](https://github.com/googleapis/google-cloud-java/issues/9156) failing (which was unrelated to the releasing modules). I've ignored the test now and will merge it in as soon as the build is done.

**Pull request merged**
