### PR TITLE
chore: enable lint (fmt-maven-plugin and checkstyle)

### PR DESCRIPTION
**Pull request by meltsufin**

### CODE REVIEW

**Comment by suztomo** [comment]
There must be some unnecessary command `basename`. The checkstyle Maven invocation succeeded.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.084 s
[INFO] Finished at: 2022-10-14T14:52:49Z
[INFO] ------------------------------------------------------------------------
basename: missing operand
Try 'basename --help' for more information.
```

**Comment by suztomo** [comment]
`basename` command here https://github.com/googleapis/google-cloud-java/blob/main/.kokoro/coerce_logs.sh#L26 This script is called in https://github.com/googleapis/google-cloud-java/blob/main/.kokoro/build.sh#L145 (after checkstyle is done)

**Comment by meltsufin** [comment]
@suztomo Apparently `build.sh` in the current form doesn't work on GitHub actions, although it works in other repos.

**Comment by suztomo** [comment]
Do not merge to main until the release goes through. (updating main branch resets the release pull request)

**Review by suztomo — APPROVED** [review]

**Pull request merged**
