### PR TITLE
Update spi classes

### PR DESCRIPTION
**Pull request by shinfan**

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
What about Pub/Sub?

**Comment by shinfan** [comment]
@garrettjonesgoogle Pubsub involves a lot more changes (due to the proto update) than other APIs so I think it would be cleaner to have a separate PR. But I am ok including it in this PR as well. Do you have a preference?

**Comment by garrettjonesgoogle** [comment]
I was only looking for your versioning changes to show up in pubsub, but it looks like pubsub wasn't touched at all here, and will retain the old version flaw.

**Comment by shinfan** [comment]
As discussed offline @michaelbausor will generate the pubsub with new protos. I will rebase this PR on top of his.

**Comment by shinfan** [comment]
Rebased with pubsub update. PTAL.

**Comment by garrettjonesgoogle** [comment]
LGTM

**Comment by shinfan** [comment]
AppVeyor tests passed. Going to merge.

**Pull request merged**
