### PR TITLE
Change location of signing tools

### PR DESCRIPTION
**Pull request by ajkannan**
This PR will be accompanied by another shortly that will update the master branch to use this new location for signing tools.

### CODE REVIEW

**Comment by mziccard** [comment]
LGTM, go ahead with the other PR, we'll merge them in a row.

**Comment by ajkannan** [comment]
I'm trying to reproduce the error on my machine, but it's taking a while because I synced my branch with the upstream, and now I'm figuring out build errors on my personal account travis testing.  You have it reproduced already, right?  How much effort would it be for you to quickly verify that the `mvn clean deploy` will work?  If it's too much effort, I'll continue testing.

**Comment by ajkannan** [comment]
Update: it looks like I'm getting closer to reproducing the error.  It's annoying that re-setting up my own CI system and tests with travis take a while though.  Will post an update soon.

**Comment by mziccard** [comment]
This is what I tried locally:
```
mvn site -DskipTests=true
mvn clean deploy -DskipTests=true -Dgpg.skip=true
```
The first command generates in all `/target` directories the "bad" jars.
The second command fails to actually deploy (missing config) but all `/target` directories have been cleaned and contain now correct jars.
It is worth doing a double check:)

**Comment by ajkannan** [comment]
I ran into a roadblock where the environment variables for staging are tested using environment variable keys I don't have (they're only in the main repo).  That local test looks good enough to me, and I'm inclined to publish the PR with master branch, removing the "skipTests" flag.  This will run the tests before deploying and error out if the cobertura bug isn't fixed.

**Comment by mziccard** [comment]
I think we can keep the `skipTests`, not sure that the tests will fail anyway. Do you?

**Pull request merged**
