### PR TITLE
Add MonitoredResourceDescriptor class and tests

### PR DESCRIPTION
**Pull request by mziccard**

### CODE REVIEW

**Comment by lesv** [comment]
LGTM

**Comment by mziccard** [comment]
`MonitoredResourceDescriptor` and `LabelDescriptor` (as well as `MonitoredResource`) entities are also used in [Stackdriver monitoring](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.monitoredResourceDescriptors/list). We should move those classes to `gcloud-java-core`. This also means that conversion methods (`toPb` and `fromPb`) will have to become public.

**Comment by lesv** [comment]
Are any of the other (API's) toPb() / fromPb() public elsewhere?

**Comment by mziccard** [comment]
> Are any of the other (API's) toPb() / fromPb() public elsewhere?

No, they are all package scope. But to reuse these classes we might have no choice.

**Comment by lesv** [comment]
Sigh - SGTM

**Comment by mziccard** [comment]
@lesv I moved the classes to the core package, PTAL

**Comment by lesv** [comment]
LGTM

**Pull request merged**
