### PR TITLE
Firestore: Update CustomClassMapper

### PR DESCRIPTION
**Pull request by schmidt-sebastian**
Update CustomClassMapper to pull in changes from https://github.com/firebase/firebase-android-sdk/pull/272

Fixes https://b.corp.google.com/issues/127664723

### CODE REVIEW

**Comment by sduskis** [comment]
There are a bunch of flips from public to default visibility and vice versa.  Do those have to be part of this PR?  Are they even meaningful for a package private class?

Please add a unit test for the changes.

**Comment by schmidt-sebastian** [comment]
> There are a bunch of flips from public to default visibility and vice versa. Do those have to be part of this PR? Are they even meaningful for a package private class?

I can revert these changes but in general I prefer to choose the narrowest possible visibility. Let me know if you want me to remove these changes.

> Please add a unit test for the changes.

In general, this particular class is not tested in the Server SDK. While we have tests for the integration, thorough testing of the CustomClassMapper exists in only in the Android SDK (https://github.com/firebase/firebase-android-sdk/blob/f040a20ba9eefbd5231f87b7757299b18d7aba54/firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java), which is the canonical source for the Mapper.  I did add some unit tests for the new errors though.

**Comment by sduskis** [comment]
Please run `mvn com.coveo:fmt-maven-plugin:format` to fix liniting issues.

**Comment by schmidt-sebastian** [comment]
Updated with Lint fix.

**Pull request merged**
