### PR TITLE
fix: Update Java-Vision IT test cases

### PR DESCRIPTION
**Pull request by lqiu96**
This is a copy of https://github.com/googleapis/java-vision/pull/976 in the Java Vision repo.

### CODE REVIEW

**Review by suztomo — APPROVED** [review]

**Comment by lqiu96** [comment]
Java-Notebook IT failures:
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.PermissionDeniedException: Operation with name "projects/gcloud-devel/locations/us-central1-a/operations/operation-1661889346833-5e77ac42c8c75-953bdec3-bcbe0f14" failed with status = GrpcStatusCode{transportCode=PERMISSION_DENIED} and message = Quota 'CPUS' exceeded.  Limit: 100.0 in region us-central1.
```
and
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: Operation with name "projects/gcloud-devel/locations/us-central1-a/operations/operation-1661889357475-5e77ac4ceef63-563cbd53-c6aa22c6" failed with status = GrpcStatusCode{transportCode=INVALID_ARGUMENT} and message = The resource 'projects/gcloud-devel/zones/us-central1-a/instances/test-notebook-instance-id-f407591a' is not ready
```

**Comment by suztomo** [comment]
For Java-Container, the message suggests to retry after wait.

**Comment by suztomo** [comment]
:tada: 

image

**Comment by lqiu96** [comment]
@suztomo Integration Tests can pass occasionally. I think we'll need to take a deeper look at some of the more flaky tests cases. Going to merge this code for vision in.

**Pull request merged**
