### PR TITLE
chore: Update Dialogflow agent display name

### PR DESCRIPTION
**Pull request by lqiu96**
This is to test #8676's IT issues without running the full suite of ITs.

Issue opened: #8681

### CODE REVIEW

**Comment by lqiu96** [comment]
It seems that the agent got renamed or replaced + recreated

https://dialogflow.cloud.google.com/#/editAgent/gcloud-devel/:
image

**Comment by lqiu96** [comment]
It seems that the `setUp()/ tearDown()` logic for these ITs doesn't create/ destroy an agent. I'm guessing this might be due to the fact that it's either expensive or extremely slow. 

We're currently relying on this one agent to be there and unchanged for the ITs: https://github.com/googleapis/google-cloud-java/blob/b2a5f7207e9f9b2f933e75ef4fd44973a234326f/java-dialogflow/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/it/ITSystemTest.java#L98

Perhaps this is something that we can continue to look into as part of the issue.

**Comment by lqiu96** [comment]
@meltsufin Do you know why it's adding in the `.gitignore` file again? I believe you recently made the change to exclude the file: https://github.com/googleapis/google-cloud-java/blob/b2a5f7207e9f9b2f933e75ef4fd44973a234326f/java-dialogflow/owlbot.py#L106

**Review by suztomo — APPROVED** [review]

**Comment by suztomo** [comment]
"generation diff / owlbot-py (pull_request)" is failing.

**Comment by suztomo** [comment]
OwlBot is adding the gitignore back somehow. https://screenshot.googleplex.com/BmRid3PQPwrMcw7

**Comment by suztomo** [comment]
Created an issue to follow up https://github.com/googleapis/google-cloud-java/issues/8683 I cannot troubleshoot it right now.

**Comment by lqiu96** [comment]
No worries! Thanks for the context @burkedavison! I could have sworn DialogFlow's IT suite was passing before and I had no idea how it started to fail.

Personally, I think it makes more sense for the test to create/ delete the agent anyways (unless it takes way too long). I can take a look in a bit to see how feasible it is. If not, I can just rename the agent to what it was before and delete this PR. We also have the owlbot issue #8683 to investigate.

**Comment by lqiu96** [comment]
Actually on second thought, I'm not sure how I could make creation/ deletion work for parallel invocations of ITs. Given the quota limitations, it would make sense to only have one agent. Does anyone have any objections if I rename this agent back to `google-cloud-java-tests`?

@burkedavison @suztomo @meltsufin

**Comment by meltsufin** [comment]
@lqiu96 No objections. Go ahead with the rename.

**Comment by suztomo** [comment]
Does "owlbot:ignore" label work? Trying.

**Comment by lqiu96** [comment]
I've renamed the agent back to `google-cloud-java-tests`. Going to create a new PR to fix: `modified_files=$(git diff --name-only "${KOKORO_GITHUB_PULL_REQUEST_TARGET_BRANCH}...${KOKORO_GITHUB_PULL_REQUEST_COMMIT}")`. 

Closing this PR. We can address the issue separately.

**Pull request closed without merging**
