### PR TITLE
Add encrypted json credentials file

### PR DESCRIPTION
**Pull request by mziccard**
This PR adds an encrypted JSON credentials file to the travis branch to be used for integration tests, as required by #211.

### CODE REVIEW

**Comment by jgeewax** [comment]
Where is the key for this stored/

**Comment by mziccard** [comment]
As an environment variable in travis, see [here](https://travis-ci.org/GoogleCloudPlatform/gcloud-java/settings). This was created with the command:
```
travis encrypt-file gcloud-devel-travis.json
```
And can be decrypted with:
```
openssl aes-256-cbc -K $encrypted_56010ceb7eb8_key -iv $encrypted_56010ceb7eb8_iv -in gcloud-devel-travis.json.enc -out gcloud-devel-travis.json -d
```

**Comment by jgeewax** [comment]
LGTM then

**Comment by aozarov** [comment]
@mziccard We already have an encrypted file. would that be an issue - considering [this](http://docs.travis-ci.com/user/encrypting-files/#Encrypting-multiple-files)?

**Comment by aozarov** [comment]
Is it possible to use different names for these environment variables?
Or is there a way to add metdata/notes in Travis for each value?

Now we have 4 of them and using these names its hard to tell which one is used for what?

**Comment by mziccard** [comment]
@aozarov It's incredible [this](https://github.com/travis-ci/travis.rb/issues/239) problem has been open/closed with a workaround for ages and we still have to go for the workaround? You are right, we must encrypt everything in one file. I will have to provide the API key to @ajkannan (or he has to provide my the gpg keys) and we must do another PR for that.

**Comment by mziccard** [comment]
The variables names are chosen by travis.

**Comment by mziccard** [comment]
Close with #215.

**Pull request closed without merging**
