### PR TITLE
Make TableDataWriteChannel expose Job when upload completed

### LINKED ISSUE #1392: BigQuery: support `/upload` method for loading data from local files.
See documentation: https://cloud.google.com/bigquery/loading-data-post-request

Python, PHP, Ruby, and Node.js provide an upload-from-file method on the Table object.

This is blocking documentation samples.

### PR DESCRIPTION
**Pull request by mziccard**
This fixes #1392

### CODE REVIEW

**Comment by mziccard** [comment]
> Can we tell codacy-bot to ignore unused locals in snippets?

It is doable but configuration is not exactly easy.

**Comment by mziccard** [comment]
@garrettjonesgoogle do you want to have a look?

**Comment by tswast** [comment]
@lesv PTAL

**Comment by lesv** [comment]
So the argument for not using `@Deprecated` and creating a new API is that no one could actually have used the earlier API.  Since that's the case, and presuming everyone agrees, LGTM.

**Pull request merged**
