### PR TITLE
Rename setters/getters/builders for Storage classes to meet proto conventions

### PR DESCRIPTION
**Pull request by mziccard**
This is the first of a series of PRs that update our naming conventions to meet the ones of proto/gRPC/VeneerToolkit.

Changes are:
- `property(Type property)` setters renamed to `setProperty(Type property)`
- `property()` getters renamed to `getProperty()`
- `builder()` factory methods renamed to `newBuilder()`

Previous methods are kept and deprecated for now.

### CODE REVIEW

**Comment by lesv** [comment]
Is that a google standard or a vKit thing?

**Comment by mziccard** [comment]
No Google standard that I know of (Guava in fact uses our current style). As per title, this is used in protos and VKIT. In order to be able to expose protos and VKIT classes without breaking Veneer look-and-feel we need to obey to their conventions on this.

**Comment by lesv** [comment]
Sigh - the shorter form works better in IDE's.

**Comment by mziccard** [comment]
@lesv I added 4 commits that do the following:
- Avoid deprecating package private methods, just rename them
- Update `TESTING.md` readme
- Update storage usage in `ITBigQueryTests`
- Update `google-cloud-nio` code to use renamed methods

**Comment by lesv** [comment]
LGTM - I won't be using approve / commit again.   Not quite the behavior I was looking for.

BlobInfo seems public not "package private".  But I defer to your judgement.

**Comment by mziccard** [comment]
> BlobInfo seems public not "package private". But I defer to your judgement.

Yes classes are public but methods I renamed without deprecating them should all be package-private. If that is not the case please point me to the methods so I can fix it.

**Comment by lesv** [comment]
Looked closer, never found a public, so I'm happy.

LGTM

**Comment by lesv** [comment]
LGTM

**Comment by lesv** [comment]
LGTM

**Pull request merged**
