### PR TITLE
Bump version to 0.32.0

### PR DESCRIPTION
**Pull request by andreamlin**

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
I'd prefer for the code changes to be separate from the release version bump

**Comment by andreamlin** [comment]
blocked on 2689

**Comment by andreamlin** [comment]
PTAL
everything pushed to maven :D; tmp_gh-pages updated

**Comment by amohabir** [comment]
I don't see a release or tag, while the artifacts are available in for example the central Maven repo. 

BTW, the inclusion of the BOM already helps us a lot in avoiding conflicting versions!

**Pull request merged**
