### PR TITLE
Metadata update with metageneration

### PR DESCRIPTION
**Pull request by gridcellcoder**
Make use of a new metadata map and return the updated blob.

### CODE REVIEW

**Comment by gridcellcoder** [comment]
I've already signed the CLA

**Comment by gridcellcoder** [comment]
I signed it!

**Comment by gridcellcoder** [comment]
@garrettjonesgoogle thanks have added the space and "I signed it!", will see if that works otherwise will create a new pull request.

**Comment by garrettjonesgoogle** [comment]
It might not be working because github might not be matching up notional author of the commits with your account. You might want to make sure you have all relevant e-mails registered in your github account.

**Comment by chingor13** [comment]
Closing due to age and failed CLA status.

The email in the git commits must exactly match the one used to sign the CLA.

**Pull request closed without merging**
