### PR TITLE
Cleaning gh-pages

### PR DESCRIPTION
**Pull request by ajkannan**
This PR cleans gh-pages in 3 ways:
-- Removes the extraneous "site" hierarchy, thus shortening the URL
-- Move the redirect to the latest page to the root directory
-- Remove 0.0.4 website from the root directory.  

Important: merging this PR should be synced with link updates in the other gcloud language website to avoid broken links on others' sites.  The "googlecloudplatform.github.io/site/latest/index.html" link should now become "googlecloudplatform.github.io/gcloud-java/index.html" (

Note: As far as I know, cleaning the repo requires touching a lot of files.  No code was changed in this CL except modifying "index.html" (in the root directory) to "point to 0.0.7/index.html" instead of "site/0.0.7/index.html".  If there is a better way of cleaning the repo, please let me know!

### CODE REVIEW

**Comment by ajkannan** [comment]
The resulting gh-pages directory only 3 items:
-- 0.0.6 (folder)
-- 0.0.7 (folder)
-- index.html

**Comment by ajkannan** [comment]
Demo can be seen here: http://ajkannan.github.io/gcloud-java

**Comment by ajkannan** [comment]
cc/ @jgeewax @aozarov

**Comment by aozarov** [comment]
Looking at: https://github.com/ajkannan/gcloud-java/tree/gh-pages

This seems to still use the colored icon and resources are not yet shared. Do you plan to do that a further PR?

If we don't want to have broken links from the other pages I suggest you do that in 2 PR. First just to add the top level redirect page and then change other sites to point to the top level. After which you can do the cleanup and update the top level redirect.

**Comment by ajkannan** [comment]
Alright, I'll put this on the backburner while I get the new redirect page up and links change.  I'll also add the icon and shared resources to this PR if people don't object to adding more to this PR.

**Pull request closed without merging**
