### PR TITLE
chore: use layer 2 docker images and inherit sdk-platform-java-config as the parent

### PR DESCRIPTION
**Pull request by mpeddada1**

### CODE REVIEW

**Comment by burkedavison** [comment]
LGTM. Will approve once passing CI checks.

**Comment by mpeddada1** [comment]
Running into `Unable to read gs://cloud_devrel_public_logs/resultstore/.../build.log. Either the file does not exist or there is a permission issue.` for all three Kokoro checks.

**Comment by mpeddada1** [comment]
Turned out to be a UI issue.

**Comment by mpeddada1** [comment]
`gax: 2.39.0` which is brought in by shared-dependencies `3.21.0` is being included as expected:

```
15:52:17:029 [WARNING] Properties file at 'jar:file:///root/.m2/repository/com/google/auth/google-auth-library-oauth2-http/1.21.0/google-auth-library-oauth2-http-1.21.0.jar!/META-INF/native-image/native-image.properties' does not match the recommended 'META-INF/native-image/com.google.auth/google-auth-library-oauth2-http/native-image.properties' layout.
15:52:17:039 [INFO] Executing: /opt/graalvm-ce-java11-22.3.3/bin/native-image -cp /tmpfs/src/github/google-cloud-java/java-compute/google-cloud-compute/target/classes:/tmpfs/src/github/google-cloud-java/java-compute/google-cloud-compute/target/test-classes:/root/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/root/.m2/repository/com/google/api/grpc/proto-google-iam-v1/1.25.0/proto-google-iam-v1-1.25.0.jar:/root/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/root/.m2/repository/com/google/api/api-common/2.22.0/api-common-2.22.0.jar:/root/.m2/repository/com/google/http-client/google-http-client/1.43.3/google-http-client-1.43.3.jar:/root/.m2/repository/com/google/api/gax/2.39.0/gax-2.39.0.jar:/root/.m2/repository/com/google/http-client/google-http-client-gson/1.43.3/google-http-client-gson-1.43.3.jar:/root/.m2/repository/org/junit/platform/junit-platform-commons/1.9.3/junit-platform-commons-1.9.3.jar:/root/.m2/repository/com/google/protobuf/protobuf-java-util/3.25.1/protobuf-java-util-3.25.1.jar:/root/.m2/repository/com/google/guava/guava/32.1.3-jre/guava-32.1.3-jre.jar:/root/.m2/repository/com/google/api/gax/2.39.0/gax-2.39.0-
```

**Review by burkedavison — APPROVED** [review]

**Pull request merged**
