### PR TITLE
Shorten URL and update logo

### PR DESCRIPTION
**Pull request by ajkannan**
This PR creates a simpler link (without "site/latest" in the URL) for other gcloud language sites to link to gcloud-java landing page.  This PR also updates the logo on the current homepage to reflect the new svg logo.

The home page will look like this after the changes:
screen shot 2015-08-27 at 8 18 27 pm

### CODE REVIEW

**Comment by jgeewax** [comment]
Errr, @aozarov , can we make sure that we....

1. Get a LGTM comment for all commits
2. Don't give LGTMs until googlebot assigns `cla: yes`

?

@ajkannan I know you're a Googler - but can you make sure that you've signed the CLA with your personal address or author your commits with your @google.com address...?

**Comment by aozarov** [comment]
@jgeewax we do follow that but I think in this case googlebot was wrong and I am not sure why.

"ajkannan" git account was already associated with Google and prior PRs by the same account were marked as `cla:yes`.

**Comment by jgeewax** [comment]
It's not about the github username -- git doesn't have that concept. GitHub's UI will turn an e-mail address into a username, but Googlebot can only see the e-mail address. That means... all commits either need to be with the @google.com username, *or* Ajay needs to sign the CLA with his @gmail.com account. Make sense?

(Of course, I've lost context on this issue, so could be totally wrong here)

**Comment by ajkannan** [comment]
@jgeewax I still don't quite understand why Googlebot said I didn't sign the CLA on this PR.  I assume the email address that GH's UI gets is from my GH account "ajkannan" account, because I commit using that account and create PRs online from that account.  As far as I can remember, I followed the same login process as I do for all my other PRs, just on my work laptop rather than my desktop.

**Comment by jgeewax** [comment]
Can you show the full git log for the PR? That should show the email
address you used.... and then we can check if that email is on the list of
CLA signers.

**Comment by ajkannan** [comment]
Ah, it looks like the email was: "ajaykannan@ajaykannan-macbookpro.roam.corp.google.com."  I'll sign the CLA with that email address for future use.

**Comment by jgeewax** [comment]
Or just edit your git config to the correct email address....?

**Pull request merged**
