### PR TITLE
bug fix on duplicate label

### PR DESCRIPTION
**Pull request by jabubake**
#1994

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
LGTM after tests pass

**Comment by garrettjonesgoogle** [comment]
(Wait to merge until the rc4 release is done)

**Comment by meltsufin** [comment]
Looks like we need this fix as well. When can we expect rc5?

@gregw FYI

**Comment by jabubake** [comment]
1.0.0 got released with this fix.
But bemanasha@ reported #1994
<https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1994> in
spite of the fix I'm looking into what broke right now.

**Pull request merged**
