### PR TITLE
feat: Modules point to aggregator pom

### PR DESCRIPTION
**Pull request by lqiu96**
Add docFX profile

### CODE REVIEW

**Comment by lqiu96** [comment]
Job is failing due to `2022-07-26T19:47:58.1260449Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (checkstyle) on project google-cloud-java: Failed during checkstyle execution: Unable to find configuration file at location: license-checks.xml: Could not find resource 'license-checks.xml'. -> [Help 1]`. The root directory doesn't have a license-checks.xml file. I can copy it over to templates/ if that makes sense.

**Comment by meltsufin** [comment]
@lqiu96 Yes, these `license-checks.xml` files should probably move up to the root. We shouldn't need to duplicate them in each module.

**Review by suztomo — APPROVED** [review]
Let's see how it works.

**Review by meltsufin — APPROVED** [review]

**Comment by lqiu96** [comment]
@meltsufin FYI, I'm skipping the maven-enforcer-plugin results for the CoverageAggregator

```
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
          <skip>true</skip>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>extra-enforcer-rules</artifactId>
            <version>1.6.0</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
```
in coverage.pom.xml.

**Comment by meltsufin** [comment]
I noticed. We should also skip maven deploy for this module in the future.

**Pull request merged**
