### PR TITLE
Logging: call flush before close

### LINKED ISSUE #4783: Logging pending writes not flushed on close causing hanging
Context: https://github.com/spring-cloud/spring-cloud-gcp/issues/1608.

### PR DESCRIPTION
**Pull request by meltsufin**
Also prevent more logs to be written after close.

Fixes #4783.

### CODE REVIEW

**Comment by sduskis** [comment]
There was a similar PR in #3909.  Right now, `flush()` ought to be called, and ideally we force the flushing to occur.  Unfortunately, `flush()` just waits for a timer to complete.  @chingor13 didn't want to merge the change for the first attempt at this bug fix.  We need to figure out how to fix this for the long haul, once @chingor13 is back.

**Comment by meltsufin** [comment]
@sduskis The critical problem is that everything gets closed while there are pending API calls. Calling `flush()` before `close()` actually fixes the issue.
This is a critical issue for us in Spring Cloud GCP (https://github.com/googleapis/google-cloud-java/pull/4784) as it currently hangs apps for 5 minutes on startup as GRPC is unable to complete those pending requests after the logging service was shut down.
Unless you think there is harm in this change, can we merge this, and @chingor13 can redo the fix when he comes back?

**Comment by sduskis** [comment]
@meltsufin, I understand why this is critical.  Merging this is @chingor13's call.

**Comment by sduskis** [comment]
@meltsufin, can you please run `mvn com.coveo:fmt-maven-plugin:format` to appease the linter?

**Comment by meltsufin** [comment]
@sduskis Done.

**Comment by dzou** [comment]
@chingor13 Hey, any updates regarding your thoughts on this PR?

**Pull request merged**
