### PR TITLE
Fix StreamingBuffer to allow oldestEntryTime to be null

### LINKED ISSUE #1131: NPE when calling com.google.cloud.bigquery.BigQuery.getTable(...)
Relevant part of the exception:

```java.lang.NullPointerException
    at com.google.cloud.bigquery.StandardTableDefinition$StreamingBuffer.fromPb(StandardTableDefinition.java:113)
    at com.google.cloud.bigquery.StandardTableDefinition$Builder.<init>(StandardTableDefinition.java:147)
    at com.google.cloud.bigquery.StandardTableDefinition$Builder.<init>(StandardTableDefinition.java:119)
    at com.google.cloud.bigquery.StandardTableDefinition.fromPb(StandardTableDefinition.java:283)
    at com.google.cloud.bigquery.TableDefinition.fromPb(TableDefinition.java:172)
    at com.google.cloud.bigquery.TableInfo$BuilderImpl.<init>(TableInfo.java:157)
    at com.google.cloud.bigquery.Table.fromPb(Table.java:348)
    at com.google.cloud.bigquery.BigQueryImpl.getTable(BigQueryImpl.java:353)
```

We suspect this is happening because the table we are trying to get seems to have a streaming buffer that is empty. Here is what some of the table info looks like:

```
...
 "numBytes": "85168232",
 "numLongTermBytes": "0",
 "numRows": "144534",
 "creationTime": "1468884348851",
 "lastModifiedTime": "1469135551174",
 "type": "TABLE",
 "location": "US",
 "streamingBuffer": {
  "estimatedRows": "0",
  "estimatedBytes": "0"
 }
```

From all the documentation it looks like this maybe isn't supposed to happen at all. But, it seems to be happening here, and resulting in an NPE.

### PR DESCRIPTION
**Pull request by mziccard**
This fixes #1131.

@mtagle @criccomini this should solve your issue.

### CODE REVIEW

**Comment by criccomini** [comment]
LGTM

**Comment by criccomini** [comment]
Can you say when this patch might be released? We're currently running a patched version.

**Comment by mziccard** [comment]
@criccomini A sound guess could be end of this week. I have a bunch of issues that I plan on fixing this week and hopefully release a new version containing all of them by Friday.

**Comment by lesv** [comment]
LGTM

**Pull request merged**
