### PR TITLE
gcloud-pubsub-java: Switching dependencies, regenerating code

### LINKED ISSUE #382: In ServiceApi classes, provide a mechanism to determine if an api method call can be retried on failure
An api method call should be retryable if it is idempotent, not retryable if not idempotent. We need to figure out the best way to surface this, whether in an exception, the ApiCallable, the ClientCall, some registry, or somewhere else.

### LINKED ISSUE #383: In ServiceApi classes, provide a way to control retry settings.
For existing gcloud services, RetrySettings is used. We probably want to keep advanced settings internal, but set them to different values for individual services, probably controlled by some kind of static service configuration or code gen configuration.

### LINKED ISSUE #394: In ServiceApi classes, provide a way to control timeouts.

### LINKED ISSUE #398: In ServiceApi classes, follow the google style guide for java
http://google.github.io/styleguide/javaguide.html

Specifically, wrapping is not done correctly. This may require a fair amount of redesign and refactoring in the code generator, or maybe some kind of post-processing step, because the code generator is language-independent.

### LINKED ISSUE #400: Use pubsub fake written by the pubsub team instead of LocalPublisherImpl
It isn't available in open source quite yet.

### PR DESCRIPTION
**Pull request by garrettjonesgoogle**
- Add dependency on gax-java
- Add dependency on grpc-pubsub-v1
- Regenerating the *Api classes
- Using the emulator runner from GAX
- Updating the test accordingly

@aozarov 

fixes #400 
fixes #398 (added a formatting step after code generation)
fixes #394 
fixes #383
fixes #382

### CODE REVIEW

**Comment by mziccard** [comment]
@garrettjonesgoogle You probably already noticed but tests are failing for Java 7 with the following error:
```
com.google.gcloud.pubsub.spi.PublisherApiTest
com.google.gcloud.pubsub.spi.PublisherApiTest  Time elapsed: 0.024 sec  <<< ERROR!
java.lang.UnsupportedClassVersionError: com/google/api/gax/testing/GCloudEmulatorRunner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.google.gcloud.pubsub.testing.LocalPubsubHelper.<init>(LocalPubsubHelper.java:66)
	at com.google.gcloud.pubsub.spi.PublisherApiTest.startServer(PublisherApiTest.java:47)
com.google.gcloud.pubsub.spi.PublisherApiTest  Time elapsed: 0.024 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.google.gcloud.pubsub.spi.PublisherApiTest.stopServer(PublisherApiTest.java:53)
```

**Comment by garrettjonesgoogle** [comment]
@mziccard yes, I noticed that last night. I have rebuilt GAX to be compatible with Java 1.7 and just now updated the pom for gcloud-java-pubsub to pull the latest version.

**Comment by mziccard** [comment]
@garrettjonesgoogle nice!

BTW the tests still fail (for a different reason now). The errors are:
```
testDeleteTopic(com.google.gcloud.pubsub.spi.PublisherApiTest)  Time elapsed: 0.765 sec  <<< ERROR!
com.google.common.util.concurrent.UncheckedExecutionException: com.google.api.gax.grpc.ApiException: io.grpc.StatusRuntimeException: ALREADY_EXISTS: Topic already exists
	at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1525)
	at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1511)
	at com.google.api.gax.grpc.ApiCallable.call(ApiCallable.java:105)
	at com.google.gcloud.pubsub.spi.PublisherApi.createTopic(PublisherApi.java:427)
	at com.google.gcloud.pubsub.spi.PublisherApi.createTopic(PublisherApi.java:414)
	at com.google.gcloud.pubsub.spi.PublisherApiTest.testDeleteTopic(PublisherApiTest.java:140)

testGetTopic(com.google.gcloud.pubsub.spi.PublisherApiTest)  Time elapsed: 0.015 sec  <<< ERROR!
com.google.common.util.concurrent.UncheckedExecutionException: com.google.api.gax.grpc.ApiException: io.grpc.StatusRuntimeException: ALREADY_EXISTS: Topic already exists
	at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1525)
	at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1511)
	at com.google.api.gax.grpc.ApiCallable.call(ApiCallable.java:105)
	at com.google.gcloud.pubsub.spi.PublisherApi.createTopic(PublisherApi.java:427)
	at com.google.gcloud.pubsub.spi.PublisherApi.createTopic(PublisherApi.java:414)
	at com.google.gcloud.pubsub.spi.PublisherApiTest.testGetTopic(PublisherApiTest.java:112)
```

If my understanding of the issue is correct we should probably use something like [UUID.randomUUID()](https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html#randomUUID()) as local address to create the in-memory service. This could be addressed in a different PR.

**Comment by garrettjonesgoogle** [comment]
@mziccard We think the issue is likely to be that the emulator is not getting properly reset. We will try out a full stop/start cycle instead, and get reset fixed later.

**Comment by garrettjonesgoogle** [comment]
@mziccard update on the test - the full stop/start cycle isn't working either; we suspect that the emulator itself is somehow not clearing state like it should, so it fails intermittently. We're getting the author of the emulator involved. Do you think the PR can go through before the issue is resolved?

**Comment by mziccard** [comment]
@garrettjonesgoogle I think we can merge as intermittent errors do not depend on this PR. Feel free to merge whenever you are ready.

**Comment by garrettjonesgoogle** [comment]
@mziccard Just to clarify, is that approval to merge this pull request?

**Comment by mziccard** [comment]
Yes :)

**Pull request merged**
