### PR TITLE
Merge gcloud-java-bigquery into master

### PR DESCRIPTION
**Pull request by mziccard**
This PR adds support for BigQuery to master.
No surprises here, just commits we already reviewed before merging into the bigquery branch.

Let's just hope integration tests won't hang on load jobs!

### CODE REVIEW

**Comment by mziccard** [comment]
All contributors already signed the CLA, removing label.

**Comment by ajkannan** [comment]
I wonder if a rebase might get rid of the merge commits and pack all the commits together in a block in the master's history.  I did a rebase onto master for resource manager, and that seemed to work well.  If you think the work-to-reward ratio is small for switching to a rebase, we can merge as is.

**Comment by mziccard** [comment]
@ajkannan I would love to do that. But I did more than one fetch from master in bigquery, removing all merges would require me to do a lot of history rewrite which is a pain in the neck and might not even lead to a very clean result.

**Comment by ajkannan** [comment]
Ah I see, I'll merge as is.  Congrats, good work on BigQuery!

**Comment by aozarov** [comment]
Great Job!! Thanks @mziccard 

We also need example, is there an issue for it?

**Pull request merged**
