### PR TITLE
pubsub: clean out dead code

### PR DESCRIPTION
**Pull request by pongad**

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Could you give some context for why this code is dead?

**Comment by pongad** [comment]
Ah sorry. Most of these tests are moved to `MessageDispatcherTest`. The `isStreaming` is dead because only tests left here tests streaming, so it's always true.

The special logic in MessageReceiver is dead because no test depends on that logic anymore.

**Comment by pongad** [comment]
@garrettjonesgoogle Ping

**Comment by pongad** [comment]
cc @jba

**Pull request merged**
