### PR TITLE
chore: Single component setup

### PR DESCRIPTION
**Pull request by ddixit14**
This PR changes release-please manifest setup to single-component setup.

### CODE REVIEW

**Review by suztomo — APPROVED** [review]

**Comment by suztomo** [comment]
I thought "generation diff / release-please-config" would fail.

**Comment by suztomo** [comment]
"generation diff / root-pom" filed:

```
Running sed command. It may take few minutes.
xargs: cannot fit single argument within argument list size limit
```

**Comment by ddixit14** [comment]
> I thought "generation diff / release-please-config" would fail.

Now it is failing. But it is not required, we don't need it anyway now. We can delete it later on.

**Comment by suztomo** [comment]
Right. These files are no longer needed

Screen Shot 2022-11-09 at 3 44 19 PM

**Pull request merged**
