### PR TITLE
feat: addressvalidation new module for addressvalidation

### PR DESCRIPTION
**Pull request by alicejli**
Initial generation for new addressvalidation client library

Corrected from https://github.com/googleapis/google-cloud-java/pull/8741

Generation script:

```
python3.9 generation/new_client/new-client.py generate \
  --api_shortname=addressvalidation \
  --proto-path=google/maps/addressvalidation \
  --name-pretty="Address Validation API" \
  --product-docs="https://developers.google.com/maps/documentation/address-validation/" \
  --api-description="The Address Validation API allows developers to verify the accuracy of addresses. Given an address, it returns information about the correctness of the components of the parsed address, a geocode, and a verdict on the deliverability of the parsed address." \
  --api-id=addressvalidation.googleapis.com \
  --cloud-api=false \
  --requires-billing=true \
  --distribution-name="com.google.maps:google-maps-addressvalidation"
```

### CODE REVIEW

**Comment by suztomo** [comment]
If your shell remembers it, can you copy-paste the command?

**Comment by suztomo** [comment]
unmanaged versions check is failing.

```
11:    <version>1.5.3</version>
Found version declaration(s) without x-version-update in: ./java-addressvalidation/google-maps-addressvalidation-bom/pom.xml
---------------------------------------------------------
87:      <version>4.13.2</version>
Found version declaration(s) without x-version-update in: ./java-addressvalidation/google-maps-addressvalidation/pom.xml
---------------------------------------------------------
17:    <version>1.[5](https://github.com/googleapis/google-cloud-java/actions/runs/3438729968/jobs/5735166643#step:3:6).3</version>
[8](https://github.com/googleapis/google-cloud-java/actions/runs/3438729968/jobs/5735166643#step:3:9)8:        <version>3.0.4</version>
[12](https://github.com/googleapis/google-cloud-java/actions/runs/3438729968/jobs/5735166643#step:3:13)4:        <version>3.3.0</version>
151:        <version>3.4.0</version>
Found version declaration(s) without x-version-update in: ./java-addressvalidation/pom.xml
```

Checking.

**Comment by alicejli** [comment]
Thanks for digging in Tomo - I thought it was related to the same issue here: https://github.com/googleapis/synthtool/issues/1707?

**Comment by alicejli** [comment]
Closing as this was added here: https://github.com/googleapis/google-cloud-java/pull/8850

**Pull request closed without merging**
