### PR TITLE
Separate service configuration from application interface

### PR DESCRIPTION
**Pull request by jboynes**
The PR separates the configuration options of the service's implementation from the application-facing interface that would not normally need to interact with them.

### CODE REVIEW

**Comment by aozarov** [comment]
"Replace CR characters with newlines" should be removed from this PR.
We briefly talked about it but I did not feel we resolved it yet.
Can you describe your concern about having a common interface for all services and for returning
the options that used to construct in an issue so we can discuses it there and maybe try to get
more opinions? I thought that it might be useful so one could just maintain a reference to the service
but still be able to get its options if for example it needs to create a similar instance later on and I could not see a problem that this might cause.

**Comment by jboynes** [comment]
Its about separation of interface and implementation. The functional API to the service should not  depend on the particular implementation being used. The `Service` interface only provides functionality for configuring the implementation, which is inherently dependent on the actual implementation being configured.

Consider typical usage with common DI frameworks like CDI, Spring or Guice. The application classes would receive the functional API interface by injection and would never deal with the implementation. The configuration would be done by separate `@Configuration` classes or even XML config files.

In some environments the code using the API can run at a different privilege level than the code configuring the implementation; for example, the application code may not be granted permission to access network resources but the implementation obviously needs that. Some environments may separate the application and implementation code into different classloaders; application servers often use frameworks like OSGi to do this.

**Comment by aozarov** [comment]
>Its about separation of interface and implementation. The functional API to the service should not depend on the particular implementation being used. The Service interface only provides functionality for configuring the implementation, which is inherently dependent on the actual implementation being configured.

I understand the concept but not entirely sure if that is a real problem.
Would you not expect that service implementation to be aware of the configuration that used to create it?

Looks like each Amazon service also extends from a base service/client (AmazonWebServiceClient - which gets a common configuration) and provides some non functional methods (such as service name).

Do you think it would be better if we required each service to extend a base service but remove the service interface (and therefore not making a specific service interface extend it?)
I am totally fine with that.


>Consider typical usage with common DI frameworks like CDI, Spring or Guice. The application classes would receive the functional API interface by injection and would never deal with the implementation. The configuration would be done by separate @Configuration classes or even XML config files.

Agree. this is why it is a read-only information rather than a way to configure the service.

> In some environments the code using the API can run at a different privilege level than the code configuring the implementation; for example, the application code may not be granted permission to access network resources but the implementation obviously needs that. Some environments may separate the application and implementation code into different classloaders; application servers often use frameworks like OSGi to do this.

Yes, we can always pick and choose what we expose in the base service interface (or base class).
I would still expect implementation of the base class to have access to its configuration, no?

**Comment by aozarov** [comment]
This PR is outdated. I plan to close it and if requested create an issue for what it tried to achieve, "Separate service configuration from application interface".

**Pull request closed without merging**
