### PR TITLE
Update pom.xml version to 0.27.1-SNAPSHOT by script

### PR DESCRIPTION
**Pull request by andreamlin**

### CODE REVIEW

**Comment by andreamlin** [comment]
PTAL

**Comment by andreamlin** [comment]
Rebased on master. Diffs should make more sense (0.27.0 -> 0.27.1-SNAPSHOT)

**Comment by garrettjonesgoogle** [comment]
Could you manually bump anything that isn't bumped by the script? (includes google-cloud-dep-verification ; do a grep for 0.26.1-SNAPSHOT)

**Comment by andreamlin** [comment]
Manually replaced all occurrences of 0.26.* to 0.27.*.
PTAL

**Pull request merged**
