### PR TITLE
chore: update CodeCoverage pom.xml by running the script

### PR DESCRIPTION
**Pull request by meltsufin**

### CODE REVIEW

**Comment by suztomo** [comment]
I think this pull request is missing the script you fixed.

**Comment by meltsufin** [comment]
> I think this pull request is missing the script you fixed.

I didn't fix any script. I just re-ran the existing one.

**Comment by suztomo** [comment]
waiting for "Generated Files Sync / CoverageAggregator does not have diff from generated one"

**Comment by suztomo** [comment]
> "Generated Files Sync / CoverageAggregator does not have diff from generated one"

It worked

**Review by suztomo — APPROVED** [review]

**Pull request merged**
