### PR TITLE
BigQuery: add long term storage bytes to standard table definition.

### PR DESCRIPTION
**Pull request by shollyman**

### CODE REVIEW

**Comment by sduskis** [comment]
@shollyman, all tests are failing.  Here's something I found

> TableInfoTest.testBuilder:163 expected: java.lang.Long<43> but was: java.math.BigInteger<43>

**Comment by sduskis** [comment]
Should this change be tested in the integration test?

**Comment by shollyman** [comment]
Sorry, I dropped this when I got pulled elsewhere.  Will pick back up next week, thanks for taking a look @sduskis

**Comment by sduskis** [comment]
@shollyman, is this PR still active?

**Comment by sduskis** [comment]
> java.lang.AssertionError: expected: java.lang.Long<43> but was: java.math.BigInteger<43>
> 	at com.google.cloud.bigquery.TableInfoTest.testBuilder(TableInfoTest.java:163)

**Comment by sduskis** [comment]
I fixed the build.  It was a 1 line change, and not related to the core logic of this change, but rather a "good samaritan" type addition of a test.  I'm going to approve.

**Pull request merged**
