### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SebastianStehle**
According to the docs and source code it should be Warning

### CODE REVIEW

**Comment by sduskis** [comment]
Hello @SebastianStehle.  Thanks for the pull request.  Would you mind signing the CLA?

**Comment by SebastianStehle** [comment]
I signed it!

**Comment by sduskis** [comment]
@SebastianStehle From the limited research that I've done, `WARN` seems to be correct.  Where did you see `WARNING`?

(https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/Level.java#L59 and https://logback.qos.ch/manual/architecture.html both say `WARN`)

**Comment by SebastianStehle** [comment]
Directly from the code:

https://github.com/googleapis/google-cloud-java/blob/9b99b0f77e4d3238b275b95b201f172b1f84ab7e/google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java#L52

**Comment by sduskis** [comment]
We'll have to test this out.  Cloud Logging uses `WARNING`, but logback uses `WARN`.

@ajaaym, can you please forward this to someone?

**Comment by sduskis** [comment]
@ajaaym, can you please forward this to someone to check on WARN vs WARNING?

**Comment by ajaaym** [comment]
@sduskis yes checking.

**Comment by ajaaym** [comment]
@sduskis log back appender is transforming WARN in to WARNING needed by cloud logging.

**Comment by sduskis** [comment]
@ajaaym, thanks for the confirmation. It looks like our README is actually correct.

**Pull request closed without merging**
