### PR TITLE
Replace CR characters with newlines

### PR DESCRIPTION
**Pull request by jboynes**
Replaces standalone \r characters in these files with \n for consistency across the codebase.

### CODE REVIEW

**Comment by aozarov** [comment]
Looks good. To avoid future variant line-ending do you mind to include a .gitattributes (with text eol=lf) in this PR to force Unix line ending (see [this](https://help.github.com/articles/dealing-with-line-endings/)).

**Comment by jgeewax** [comment]
+1 to that idea @aozarov

**Comment by jboynes** [comment]
I don't mind but would point out that most[1] other projects don't have a per-repo attributes file - they leave it to the user to set the options in their git client.

[1] I checked the first five from GoogleCloudPlatform plus this is the norm on all other OSS projects I've work on.

**Comment by aozarov** [comment]
If we care about unix line ending style than I am not sure I see any wrong in doing that (and can only see the advantage of not needing any further PRs like this one). Do you?

**Comment by jgeewax** [comment]
I honestly didn't know that this was an option.... Had I known, I certainly would have encouraged it's use in the other gcloud-* repositories.....

In other words: we're saying "this repo only wants LF, not CRLF" -- sounds like a repo-specific thing, right?

**Comment by jboynes** [comment]
AIUI, this does not affect what is stored in the repo. `text eol=lf` means that when you checkout a file the line endings are converted to `LF` _even on Windows._ This can cause issues with some native editors, `Notepad` curse you ... It would be worth investigating how non-default behaviours affect various platforms - I opened #95 for that.

Whatever the outcome there we need to fix the file content in the repo. Can we pull this to do that?

**Pull request merged**
