### PR TITLE
Re-order landing page menu to put .NET first

### PR DESCRIPTION
**Pull request by mziccard**

### CODE REVIEW

**Comment by mziccard** [comment]
This fixes #1172 for next site versions, while #1182 fixes it for the latest deployed version.

**Comment by lesv** [comment]
LGTM -- at some point do you want to put this in [/docs/](https://github.com/blog/2228-simpler-github-pages-publishing) ?

**Comment by mziccard** [comment]
> at some point do you want to put this in /docs/ ?

I believe that moving all content of `gh-pages` to /docs would increase too much the size of our master branch (given that we keep also older versions).

**Pull request merged**
