### PR TITLE
Run tests for PRs to branches other than master

### LINKED ISSUE #420: Run unit tests for non-master branch PRs
Right now, we only run unit tests for PRs that are on the master branch.  We should run the unit tests.  We can optionally include a coverage report, but since PRs in other branches tend to be "work in progress" it's not as vital.

### PR DESCRIPTION
**Pull request by mziccard**
This should fix #420.
Notice that #420 will be fixed only when this is merged/rebased in all other branches.

### CODE REVIEW

**Comment by jgeewax** [comment]
Just out of curiosity, if someone submits a PR (that none of us review) that echo's our encrypted keys in plaintext, what's the point of encrypting the keys ?

Should we have to approve it before the tests are run by OUR Travis instance?

**Comment by ajkannan** [comment]
@jgeewax Right now, we only decrypt the keys in non-PR Travis builds (see [here](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/utilities/verify.sh#L9)), so I don't think that particular scenario can happen right now.  If we happen to change the CI build code, we should be sure to decrypt the keys only when merging in a PR. 

@mziccard Do you think we should remove the check for whether the branch is the `master` branch [here](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/utilities/verify.sh#L7).

**Comment by jgeewax** [comment]
Cool - so long as we're not opening up a gaping security hole :)

**Comment by mziccard** [comment]
@jgeewax Everything that we encrypt/decrypt needs travis encryption variables that are only available for non-PR builds (AFAIK). So decrypting the keys in a PR should not be possible.

@ajkannan I thought to leave integration tests only for master but you are right we should run them (if any) also in other branches. I'll fix this!

**Comment by aozarov** [comment]
Yes @mziccard is right. see [this](https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests).

**Pull request merged**
