### PR TITLE
Pubsub subscriber owns its own Deque.

### PR DESCRIPTION
**Pull request by sduskis**
This PR is part of #4514.

### CODE REVIEW

**Comment by sduskis** [comment]
Windows 8 tests keep failing for unrelated reasons.

**Comment by sduskis** [comment]
@dpcollins-google, can you please take a look at this PR?

**Comment by sduskis** [comment]
@kolea2 can you PTAL?

**Comment by dpcollins-google** [comment]
sduskis@ I have no problem with this, but I can't be a reviewer.  I did essentially the same thing in 4546@, I'm trying to build a chain of reviews making small changes.

**Pull request closed without merging**
