### PR TITLE
Pull updates from master branch

### PR DESCRIPTION
**Pull request by ajkannan**

### CODE REVIEW

**Comment by ajkannan** [comment]
cc @mziccard @aozarov looks like I need confirmation to make googlebot CLA happy.

**Comment by mziccard** [comment]
You can use my commits :)

**Comment by aozarov** [comment]
Same here.

**Comment by ajkannan** [comment]
@mziccard Do you have a lot of experience with git?  I used `git fetch`/`git merge` in order to update the `update-datastore` branch with changes made in `master`.  I want to make sure that I won't make life difficult down the road when the `update-datastore` branch is merged into the master.  The commit hashes in this PR look the same as in the master branch (besides an additional "merge commit" at the end of the PR commits to deal with conflicts).  The other option I've read about online is to do `git rebase` to put all `update-datastore` changes after the `upstream/master` changes.  Do you forsee any issues with this PR or have an opinion on which approach is preferable?

**Comment by jgeewax** [comment]
In general, you shouldn't rebase anything once it's been shared with the
world.

Private branches it's OK, but anything we've done publicly on the main line
shouldn't be rebased later. Here's an interesting write-up for future
reference:
http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/#a-word-on-re-writing-history:f287424823c961f4275aa77b76a65037

**Comment by mziccard** [comment]
If we do consider the `update-datastore` branch as "public" and possibly being used by users then we should avoid `git rebase`. `git rebase` requires then pushing non fast forward changes to a branch (`git push -f`) which might cause troubles to users using/working on that branch.

However, for cases like this I usually prefer using `git rebase`: `update-datastore` is ahead of master of a few commits (~20) while behind of a considerable amount (~200). Doing a merge with master keeps the same commits (as you said hashes match) but adds a not-so-desirable merge commit at the end. If we are going to do this "updates pull" several times in the future we will end up with several merge commits that just add dirt to the history. Rebasing instead moves all ahead commits on top of master's head, thus avoiding ugly merge commits.

I use `git rebase` very often to move PRs forward when they happen to conflict with master. But PRs are private branches and @jgeewax is right that `git rebase` should be avoided in general on public branches.

**Comment by ajkannan** [comment]
Alright, in that case I'll stick with the `git merge` in this case.  Thanks for the input @jgeewax and @mziccard

**Comment by ajkannan** [comment]
[Amending my previous comment] Actually, since nobody probably is using this particular branch (v1beta3 isn't released yet), do we consider this branch to really be public?  If not, I'll change this PR to do a rebase.

**Comment by ajkannan** [comment]
Update: I will go with a `rebase` instead of a `merge`.  Will update the PR soon.

**Comment by ajkannan** [comment]
Having attempted the rebasing solution, I think it's unnecessarily complicated compared to the merge.  Because the v1beta3-related commits are given new hashes, they don't merge into the upstream/update-datastore branch without merge conflicts.  I see two ugly ways to get around this:
1) Rebase `update-datastore` onto `master`, but then push to a new upstream branch.  Then delete the old `upstream/update-datastore` branch.
2) Create one PR to reset (hard) the `upstream/update-datastore` branch to the commit before the branch was created.  Then create a second PR for the rebase. 
Both solutions seem unnecessarily complicated compared to the merge, so I updated this PR to use a merge instead.

**Comment by ajkannan** [comment]
@aozarov I diffed this PR against upstream/master, and the only changes are in `gcloud-java-datastore`, and one change in `gcloud-java-core` that was intended (ensuring that namespace could not be set to null).  No changes appeared in `gcloud-java-storage`.  I also ran all the tests and everything's passing.

**Pull request merged**
