### PR TITLE
Initial GAX submission - generated API-independent classes only

### PR DESCRIPTION
**Pull request by garrettjonesgoogle**
Except for pom.xml, all of these files are generated from api-independent proto files, and will never need to be modified manually.

### CODE REVIEW

**Comment by aozarov** [comment]
AFAIK, there is no standard for the location of generated code/resources, but did you consider this [suggestion](http://stackoverflow.com/questions/22912900/location-of-generated-source-files-for-maven-directory-structure)? (basically have generated as a top level like `target`).

**Comment by garrettjonesgoogle** [comment]
I did not consider that suggestion. The accepted answer there suggests `generated/src/main` for generated files, which I am personally fine with. Would you like to go with that?

**Comment by aozarov** [comment]
Also, unless you think we will manage to move it to its own repository before merging into main, we should add a `README.md` (similar to that one in `core`).

**Comment by aozarov** [comment]
Yes, I liked `generated/src/main` better for the reasons mentioned there.

**Comment by aozarov** [comment]
I don't think we need to include com.google.protobuf as these are already publicly available via [maven](http://central.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0-beta-1/).

**Comment by garrettjonesgoogle** [comment]
I have changed the following things:

* removed com.google.protobuf classes (I confirmed everything works without them checked in here)
* moved everything from src/generated to generated/src
* added a README.md file

The pull request seems to be misbehaving with my forced rewrite of the commit history. I'll submit a new pull request instead.

**Comment by garrettjonesgoogle** [comment]
Replacement pull request: https://github.com/GoogleCloudPlatform/gcloud-java/pull/316

**Pull request closed without merging**
