### PR TITLE
chore: Run ITs on diffs between latest and the branching commit

### PR DESCRIPTION
**Pull request by lqiu96**
Tries to fix: https://github.com/googleapis/google-cloud-java/issues/8640

Only run AI-Platform/ Compute Native Tests when there are changes to those modules.

### CODE REVIEW

**Comment by meltsufin** [comment]
I think you also need to fix the root pom logic. The root pom is now in `google-cloud-jar-parent`.

**Comment by lqiu96** [comment]
> I think you also need to fix the root pom logic. The root pom is now in `google-cloud-jar-parent`.

Ah nice catch! I'll update that.

**Comment by meltsufin** [comment]
`google-cloud-pop-parent` too probably.

**Comment by lqiu96** [comment]
> `google-cloud-pop-parent` too probably.

Ah yep, I see that shared-config is in `pom-parent` and not `jar-parent`. Adding in now.

**Comment by suztomo** [comment]
Does this take care of native image test?

**Comment by lqiu96** [comment]
> Does this take care of native image test?

Presubmit native tests only run AI Platform or Compute. The nightly job runs all modules and doesn't use the existing diff logic.

**Comment by meltsufin** [comment]
> > Does this take care of native image test?
> 
> Presubmit native tests only run AI Platform or Compute. The nightly job runs all modules and doesn't use the existing diff logic.

I guess @suztomo is asking whether these would be skipped unless there are changes to the parent poms or compute/aiplatform.

**Comment by lqiu96** [comment]
> > > Does this take care of native image test?
> > 
> > 
> > Presubmit native tests only run AI Platform or Compute. The nightly job runs all modules and doesn't use the existing diff logic.
> 
> I guess @suztomo is asking whether these would be skipped unless there are changes to the parent poms or compute/aiplatform.

Ah I see, I was resolving a different issue with the diffs. I'll add in the diffs for native tests

**Comment by suztomo** [comment]
Thanks. Yes, I feel most of the presubmit native image test run (java-compute and java-aiplatform) in most pull requests are unnecessary.

**Comment by lqiu96** [comment]
> Thanks. Yes, I feel most of the presubmit native image test runs (java-compute and java-aiplatform) in most pull requests are unnecessary (#8640).

Yeah, I agree that the module specific native checks don't need to be run on every PR, especially ones that don't affect Compute/ AI-Platform. With this change in, we should pay more attention to the nightly builds.

**Review by suztomo — APPROVED** [review]

**Pull request merged**
