### PR TITLE
Rename com.google.gcloud to com.google.cloud

### PR DESCRIPTION
**Pull request by ajkannan**
Related to #877.  Does not close the issue because the READMEs are left unchanged by this PR.  I will update the READMEs to use com.google.cloud once we release an artifact, otherwise users may get confused.

### CODE REVIEW

**Comment by mziccard** [comment]
I see that in READMEs we still have links to old javadoc and files (try searching `com/google/gcloud` in the files). Is this intended? I believe these links should be updated.

Also as soon as we merge this we should release new artifacts so that README links to javadoc are not broken.

**Comment by ajkannan** [comment]
Fixed README links.  And yup, as soon as this gets merged, I plan on releasing artifacts.

**Comment by mziccard** [comment]
README links seem to be fixed now. Since we merged #858 we should update the [URL](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/utilities/after_success.sh#L22) we use to check whether the artifact is already deployed or not.

**Comment by mziccard** [comment]
Also is there something we can do to make it more clear that we renamed our `group` and `package` to users that already have `gcloud-java` as a dependency?

I am thinking about adding some temporary text on top of http://googlecloudplatform.github.io/gcloud-java/ and our main `README.md`. /cc @jgeewax @aozarov

**Comment by ajkannan** [comment]
Good catch on the URL update.  I rebased, fixed that link, and grepped for "com.google.gcloud" and "com/google/gcloud" and found no results.  

I think it's a good idea to add some temporary text on the website and our README, they're both pretty common entrypoints to our repo according to our [traffic stats](https://github.com/GoogleCloudPlatform/gcloud-java/graphs/traffic).  I'll also add a note at the top of our release notes.

**Comment by mziccard** [comment]
This looks good to me. I couldn't find any more stale naming. Text on top of site and README could be added in the release commit, right? Do you think it's worth adding it on top of each README?
I was thinking about something like:

> "As of April 12th, 2015, `gcloud-java`'s group ID and base package were renamed to `com.google.cloud`. If you haven't already please update your dependency."

To be placed just before where we show our dependency code. Could this work?

**Comment by ajkannan** [comment]
That text sounds good to me.  I'll add that in the release commit.

**Comment by ajkannan** [comment]
Just a note: after we release with this packaging change, we'll have to update the external applications (in java-docs-samples and getting-started-java) and also the links in cloud.google.com to particular gcloud-java classes.

**Comment by aozarov** [comment]
Looks good. I think we only need to note in the release-notes, main readme page and maybe in the site page. FYI, I did a test and deployed it to [snapshots](https://oss.sonatype.org/content/repositories/snapshots/com/google/cloud/).

**Comment by aozarov** [comment]
Feel free to merge when you are ready.

**Pull request merged**
