### PR TITLE
bigquery: make FieldValue publicly construct-able

### LINKED ISSUE #2880: FieldValue.of is not public
For some reason FieldValue "of" method is not "public static" which means I can't create an instance of FieldValue. I can create instances of other, similar objects like Field, Schema, etc. though.

This is major problem, because it means you can't create bigquery result objects for things like testing. Could we please make this available?

### PR DESCRIPTION
**Pull request by pongad**
so make testing easier for users. Fixes #2880.

### CODE REVIEW

**Comment by pongad** [comment]
@vam-google Are you OK with this being public?

**Comment by tswast** [comment]
Hmm, I think something like https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1370 would better cover the desired use case for testing specific query / table values than exposing this as public would. Albeit, that is a bigger project than changing visibility.

**Comment by pongad** [comment]
I agree; doing that would definitely be better. I guess there are 2 options.

1. We can go ahead with this PR, and mark the newly-public methods `@BetaApi`. When POJO works, we deprecate them.
2. We close #2880 as dup of #1370, which is now tracked by feature wiki.

I'll defer to you on the decision. However, I'm slightly leaning towards (1). My reasoning is that, right now, users have to deal `FieldValueList.get` anyway. If you know what to expect from `get`, calling `of` isn't too terrible.

**Comment by tswast** [comment]
Yeah, (1) makes sense. I agree to keep it as `@BetaApi` for now.

**Pull request merged**
