### PR TITLE
Rename setters/getters/builders for Compute classes to meet proto conventions

### PR DESCRIPTION
**Pull request by mziccard**

### CODE REVIEW

**Comment by lesv** [comment]
I'm getting a 404 when I click on "Files changed"

**Comment by mziccard** [comment]
> I'm getting a 404 when I click on "Files changed"

Probably a transient github issue. Seems to be fixed now.

**Comment by mziccard** [comment]
@lesv are you still getting the 404?

**Comment by lesv** [comment]
No - it got set aside.  I'll try to finish today.

**Pull request merged**
