### PR TITLE
Add getDefaultInstance method to StorageOptions and DatastoreOptions

### PR DESCRIPTION
**Pull request by mziccard**
This follows from #342 and adds a static `getDefaultInstance` method to both `StorageOptions` and `DatastoreOptions`.

### CODE REVIEW

**Comment by ajkannan** [comment]
In v0.0.10, it looks like the method was called `defaultInstance()` in Datastore instead of `getDefaultInstance()`.  However, in all other places in the API (`RetryParams` and `ExceptionHandler`), the method is called "getDefaultInstance", which is consistent with the method names chosen here.  This looks good to me, but if @aozarov prefers to leave out the "get" in method names like this, then we should probably standardize for those two objects as well.

**Comment by mziccard** [comment]
I might be wrong but i cannot find any `defaultInstance` in `DatastoreOptions`.

**Comment by mziccard** [comment]
@ajkannan I picked `getDefaultInstance` for consistency with `RetryParams` and `ExceptionHandler`. I we decide to remove the `get` part I'll take care of removing it everywhere.

**Comment by ajkannan** [comment]
Sounds good.  And yes, the `defaultInstance()` was accidentally removed in 0.0.11; just for reference, here's a link to the method in the [0.0.10 javadoc](http://googlecloudplatform.github.io/gcloud-java/0.0.10/apidocs/com/google/gcloud/datastore/DatastoreOptions.html).

**Comment by aozarov** [comment]
+1 for having it as `defaultInstance()`. I prefer it because it is shorter, consistent with its own file and overall more consistent with our style.

`RetryParams` and `ExceptionHandler` were copied and modified from another [library](https://github.com/GoogleCloudPlatform/appengine-gcs-client/tree/master/java/src/main/java/com/google/appengine/tools/cloudstorage) I worked on before but I neglected to update it to conform our style. Would be great if we can take care of that as well...

**Comment by mziccard** [comment]
I renamed the methods to `defaultInstance`, updated the READMEs and made both `RetryParams` and `ExceptionHandler` conform with our code style.

**Comment by aozarov** [comment]
Great, thanks. Shall we change this [file](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/src/site/resources/index.html) as well?

and replace ```DatastoreOptions.builder().build()``` with ```DatastoreOptions.defaultInstance()```?

**Comment by mziccard** [comment]
Updated also site's landing page.

**Pull request merged**
