### PR TITLE
Fix exported variable scope issue

### PR DESCRIPTION
**Pull request by ajkannan**
Addresses the issue at the bottom of #264

### CODE REVIEW

**Comment by mziccard** [comment]
Have you had the chance to check that `source` works as expected in travis? If so I think we can merge!

**Comment by ajkannan** [comment]
I haven't actually, let me quickly check that and I'll comment if/when it's successful.

**Comment by ajkannan** [comment]
Yup, sourcing works as expected in travis.

**Comment by mziccard** [comment]
Looks good.

**Pull request merged**
