### PR TITLE
GAPIC Compute java library

### PR DESCRIPTION
**Pull request by andreamlin**
First gapic for Compute client.

Adds gax:testlib to google-cloud-bom/pom.xml.

### CODE REVIEW

**Comment by andreamlin** [comment]
Blocked on https://github.com/GoogleCloudPlatform/google-cloud-java/pull/3102, which is waiting for newest gax-java packages to be released in maven.

**Comment by andreamlin** [comment]
This was generated from toolkit/master. The google-java-format util was run on the output. The output was copied into google-cloud-java/google-cloud-compute.

**Comment by andreamlin** [comment]
@garrettjonesgoogle Would you know how to fix the build compile errors?
For the Appveyor failure, there's apparently a missing file HttpsHealthCheck.java, even though it does exist and it's in the same package as the file where the error occurs.
For the CircleCI Java 7 failure, there's an out of memory error during the compile process that doesn't occur in the Java 8 build. I can look into the circleci config to see if there's a problem there.

**Comment by andreamlin** [comment]
Upped the Java heap size for CircleCI openjdk_7 to 1024m from 256m and that fixed the out of memory error during compile.

**Comment by andreamlin** [comment]
So the problem with the Appveyor build is that it runs on a Windows machine, which does *not* have a case sensitive file system. This PR includes separate HTTPHealthCheck.java and HttpHealthCheck.java, but one overwrites the other when imported into Appveyor's machine.

**Comment by andreamlin** [comment]
PTAL

**Comment by andreamlin** [comment]
This assumes https://github.com/googleapis/gapic-generator/pull/1956 is checked in.

**Comment by andreamlin** [comment]
PTAL

**Comment by garrettjonesgoogle** [comment]
🎉

**Pull request merged**
