### PR TITLE
Minor Bash improvements

### PR DESCRIPTION
**Pull request by Androbin**
* Remove misplaced token
* Apply recommendations of static analysis tool

https://github.com/koalaman/shellcheck/wiki/SC2166
https://github.com/koalaman/shellcheck/wiki/SC2206
https://github.com/koalaman/shellcheck/wiki/SC2068

### CODE REVIEW

**Comment by Androbin** [comment]
@vam-google Any updates on this?

**Comment by Androbin** [comment]
@garrettjonesgoogle Any updates on this?

**Comment by garrettjonesgoogle** [comment]
What we actually want to do long-term is transition from maven to gradle for the build system, which would allow us to pull all scripting into one place (build gradle files). https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1587

**Comment by Androbin** [comment]
@garrettjonesgoogle Okay, I understand that.

**Pull request closed without merging**
