### PR TITLE
Add support for Google Translate

### PR DESCRIPTION
**Pull request by mziccard**
Nothing new here, just merging the translate-alpha branch, all commits have already been reviewed.

/cc @lesv

### CODE REVIEW

**Comment by lesv** [comment]
LGTM - once travis is happy.  Are there issues for the licenses that dependency-ci are seeing?

**Comment by mziccard** [comment]
> Are there issues for the licenses that dependency-ci are seeing?

Dependency-ci is complaining  about `javax.inject` not being licenced, but that's not true so I guess it's just a bug on their side.

**Comment by lesv** [comment]
Travis is using a very old version of Java8.

**Comment by lesv** [comment]
I see a test for Listing country codes, they would like an actual example of it.

**Comment by mziccard** [comment]
> I see a test for Listing country codes, they would like an actual example of it.

Yes there's a test (actually two) for listing supported languages. There are also snippets for that, see `listSupportedLanguages` and `listSupportedLanguagesWithTarget` in `DetectLanguageAndTranslate`.

**Comment by lesv** [comment]
Cool - It's just a different name.

**Pull request merged**
