### PR TITLE
test: skipNativeTests in java-core

### LINKED ISSUE #9075: Nightly Failure: google-cloud-core contains no tests during -Pnative build
Nightly is failing due to `google-cloud-core` being built with `-Pnative` profile, but not containing any (activated) tests.

`Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.18:test (test-native) on project google-cloud-core: Execution test-native of goal org.graalvm.buildtools:native-maven-plugin:0.9.18:test failed: Test configuration file wasn't found.`

https://source.cloud.google.com/results/invocations/588e3ab9-7721-462f-95a8-10b8c5b537b6/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-cloud-java%2Fnightly%2Fgraalvm-sub-jobs%2Fnative%2Fgraalvm-native-2/log

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #9075 

The java-core module itself does not have integration tests and thus cannot be tested with native image plugin. Instead, the client libraries that use this java-core module have integration tests on native image.

# How I confirmed the effect

The following command, which was failing in #9075, now succeeds:

```
~/google-cloud-java $ mvn -pl java-core -am -Dclirr.skip=true  -Denforcer.skip=true  -Dcheckstyle.skip=true -Dflatten.skip=true -Danimal.sniffer.skip=true -Pnative test

...

[INFO] --- native-maven-plugin:0.9.18:test (test-native) @ google-cloud-core-parent ---
[INFO] Skipping native-image tests (parameter 'skipTests' or 'skipNativeTests' is true).
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Google Cloud POM Parent 1.4.0-SNAPSHOT ............. SUCCESS [  0.866 s]
[INFO] Google Cloud JAR Parent 1.4.0-SNAPSHOT ............. SUCCESS [  0.297 s]
[INFO] Google Cloud Core Parent 2.9.5-SNAPSHOT ............ SUCCESS [  0.037 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.151 s
[INFO] Finished at: 2023-02-03T10:14:10-05:00
[INFO] ------------------------------------------------------------------------
```

# Excluding java-core in modified module list

This pull request temporarily removes java-core module from modified module list until  https://github.com/googleapis/google-cloud-java/issues/9088 is resolved.

### CODE REVIEW

**Review by burkedavison — APPROVED** [review]

**Review by mpeddada1 — APPROVED** [review]
Nice!

**Comment by suztomo** [comment]
"Kokoro Test Integration" failed

```
com.google.api.gax.rpc.FailedPreconditionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: One or more users named in the policy do not belong to a permitted customer.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:102)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:98)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:574)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:541)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:736)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.pubsub.v1.TopicAdminClient.setIamPolicy(TopicAdminClient.java:1450)
		at com.google.cloud.pubsub.v1.TopicAdminClient.setIamPolicy(TopicAdminClient.java:1481)
		at com.google.cloud.notification.it.ITSystemTest.testNotifications(ITSystemTest.java:111)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
		at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		... 1 more
Caused by: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: One or more users named in the policy do not belong to a permitted customer.
	at io.grpc.Status.asRuntimeException(Status.java:539)
	... 14 more
```

https://source.cloud.google.com/results/invocations/be9c6640-1183-4224-aa72-1350077ddf88/targets/github%2Fgoogle-cloud-java%2Fjava-notification%2Ftarget%2Ffailsafe-reports/tests

Retrying.

**Comment by burkedavison** [comment]
@suztomo : Re "Integration Test Failures"...

Terraform says:
```
Planning around modules java-core
```
Yet `java-notification` integration tests are being run (and failing) due to not having the associated Terraform setup running.

**Comment by suztomo** [comment]
"Kokoro - Test: Integration — Build successful" (because java-core is now excluded from modified module list temporarily)

**Review by mpeddada1 — APPROVED** [review]

**Pull request merged**
