### PR TITLE
Firestore: Migrate client to use v1 gapic client / protos.

### PR DESCRIPTION
**Pull request by mikelehen**

### CODE REVIEW

**Comment by mikelehen** [comment]
This is currently based on https://github.com/googleapis/google-cloud-java/pull/4410 but we probably want to merge that first, then rebase this on master and merge it.

**Comment by igorbernstein2** [comment]
I hit the same issue while working on the bigtable client. I opened #4438 to track it

**Comment by mikelehen** [comment]
@kolea2 Can you add the "kokoro:force-run" label again? 😄

**Comment by mikelehen** [comment]
Actually, nevermind. I probably can merge master / re-push.

**Comment by kolea2** [comment]
@sduskis do you know the what the spanner test failure is?

**Comment by mikelehen** [comment]
Thanks!

**Pull request merged**
