### PR TITLE
Add LogEntry class, Severity enum and tests

### PR DESCRIPTION
**Pull request by mziccard**

### CODE REVIEW

**Comment by mziccard** [comment]
@lesv would you mind having a look? Thanks!

**Comment by lesv** [comment]
LGTM

**Comment by lesv** [comment]
P.S. Do you have an ETA of when Logging will be published?

**Comment by mziccard** [comment]
@lesv I trust it will be ready by the end of the month

**Comment by lesv** [comment]
Thanks -- Still LGTM

**Pull request merged**
