### PR TITLE
DO NOT MERGE: regenerating spi layer - GAX 0.0.22

### PR DESCRIPTION
**Pull request by garrettjonesgoogle**
This is a non-working PR that only includes updates to the SPI
classes. The hand-written layer still needs to be updated.

### CODE REVIEW

**Comment by mziccard** [comment]
@garrettjonesgoogle thanks! I started working on the integration on this changes into `google-cloud-java` but I realized that you removed some classes form GAX:
```java
import com.google.api.gax.testing.DownloadableEmulatorRunner;
import com.google.api.gax.testing.GCloudEmulatorRunner;
import com.google.api.gax.testing.LocalServiceHelper;
```

Those classes were used in our `LocalPubSubHelper` (which was originally written by you and @shinfan).
I understand that you are using a mocking framework to test autogen code. However, should we add those classes back to GAX or should I implement them in `google-cloud-java`?

**Comment by garrettjonesgoogle** [comment]
The auto-generated testing code already covers everything in the spi layer that the emulator test was covering, so it had become redundant from our perspective. Emulator support has been removed from our testing strategy because it doesn't scale as well. If you still want these tests in `google-cloud-java` to support the pubsub tests, I would recommend copying them in.

**Comment by mziccard** [comment]
Replaced by #1379

**Pull request closed without merging**
