### PR TITLE
Expose Object serialization for internal consumers

### PR DESCRIPTION
**Pull request by schmidt-sebastian**
This allows internal teams to create DocumentSnapshots from POJOs, Maps and the Proto.

### CODE REVIEW

**Comment by schmidt-sebastian** [comment]
@BenWhitehead Is there anything special I need to do regarding the formatting? I have re-installed my Maven dependencies and `mvn com.coveo:fmt-maven-plugin:format` doesn't show me a diff anymore, yet the verification still fails.

**Comment by schmidt-sebastian** [comment]
> @BenWhitehead Is there anything special I need to do regarding the formatting? I have re-installed my Maven dependencies and `mvn com.coveo:fmt-maven-plugin:format` doesn't show me a diff anymore, yet the verification still fails.

To be clear, it did format the change the first time around.

**Comment by BenWhitehead** [comment]
@schmidt-sebastian The new file https://github.com/googleapis/google-cloud-java/pull/6085/files#diff-c1b66da3ed37700b15f5fb4c57e0328dR1 looks like it's missing a copyright header and that's why it's failing.

**Comment by schmidt-sebastian** [comment]
Thanks :) It's passing now.

**Pull request merged**
