### PR TITLE
Add support for Google Cloud Pub/Sub

### PR DESCRIPTION
**Pull request by mziccard**
This PR takes all commits from the `pubsub-alpha` branch and rebases them on top of master.

No news here, all commits but the last one have already been reviewed.

The last commit does some dependency cleanup.

### CODE REVIEW

**Comment by mziccard** [comment]
@lesv do you mind having a look at the latest commit? (previous commits have already been reviewed)

**Comment by lesv** [comment]
LGTM - on the last commit.

**Comment by mziccard** [comment]
@lesv thanks for the pass, I just added one more commit (aefce68) to fix a broking link in the main README. You can see it fixed [here](https://github.com/mziccard/gcloud-java/blob/add-pubsub-support/README.md). PTAL

**Comment by lesv** [comment]
LGTM

**Pull request merged**
