### PR TITLE
Update gax javadoc link to point to latest.

### PR DESCRIPTION
**Pull request by kolea2**

### CODE REVIEW

**Comment by chingor13** [comment]
Is this actually what we want to do? If this library depends on 1.35.0, shouldn't these links always point to the 1.35.0 docs instead of whatever the latest is?

**Comment by kolea2** [comment]
True, I was initially looking at this pull request (https://github.com/googleapis/google-cloud-java/pull/2991) which references eventually switching gax.version to latest, but I see your point. Maybe we could look into having one variable for gax.version instead of updating it just for the javadoc. What do you think?

**Comment by chingor13** [comment]
It may be difficult as we need to specify the gax version in the bom and google-cloud-clients and they do not currently share a parent (which would let us share properties).

If you can find a way to have us maintain the version in a single place, that would be fantastic.

**Comment by chingor13** [comment]
Specifying the version in one place is not unique to gax. We should create a cleanup issue to do this across all of our dependencies where possible.

**Comment by kolea2** [comment]
Created issue #4223 for this!

**Pull request closed without merging**
