### PR TITLE
Add directions for release notes

### PR DESCRIPTION
**Pull request by ajkannan**

### CODE REVIEW

**Comment by stephenplusplus** [comment]
LGTM. It might be helpful to provide a basic template for your release notes to follow, or a simple note about "keeping consistent with the previous release notes". In Node land, it would look like:

--

#### Updating

```sh
$ npm install gcloud@0.25.1
```

- [Documentation](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.25.1)
- [Report an issue](https://github.com/GoogleCloudPlatform/gcloud-node/issues)


#### :warning: Breaking Changes

##### [Easily understood heading about something to take note of]

###### Before
```js
// Code before
```

###### After
```js
// Code after
```


#### Plural category of change [Fixes, Features, Extras, Documentation, etc]

- **Service ([Datastore, Storage, etc])** (#[issue number], #[pr number]): One-line description of change.


#### Thank you!

[If applicable, @ tag non-Googler contributors (bug reporters, PR senders)]

If you catch any regressions, please open an issue. See the [Contributing](https://googlecloudplatform.github.io/gcloud-node/#/contributing) guide for how to get started.

**Comment by aozarov** [comment]
Do you think we should add labels or use milestones for pull requests to help identify what we should be mentioning in the release notes?

My assumption is that people that worked on a PR (creator and  reviewer) will know better if something should be included and also make sure to have an appropriate description.

Or do you think all PRs between releases should be mentioned? If so, are you familiar with a tool ,maybe that uses the github [API](https://developer.github.com/v3/), that can do it?

**Comment by aozarov** [comment]
Actually, I realize that node is using the draft option and, I assume, update it for each relevant merged PR? That sounds like a better option to me than using labels. What do you think?

**Comment by ajkannan** [comment]
Using the draft option SGTM

**Pull request merged**
