### PR TITLE
Update and fix gcloud-java-logging

### PR DESCRIPTION
**Pull request by shinfan**
- Update gcloud-java-logging generated code by latest proto and gapi-tools
- Update pom to add new dependencies to grpc-logging on maven
- Add baseline
- Update unit tests based on the new surface

Issues to resolve: https://github.com/GoogleCloudPlatform/gcloud-java/issues/769, https://github.com/GoogleCloudPlatform/gcloud-java/issues/771

### CODE REVIEW

**Comment by shinfan** [comment]
I have updated the PR description to be specific.

**Comment by mderka** [comment]
There are some unused imports here:

- `import com.google.api.gax.grpc.ApiCallSettings;` in ConfigServiceV2Api
- `import com.google.api.gax.grpc.ApiCallSettings;` in LoggingServiceV2Api
- `import com.google.api.gax.grpc.ApiCallSettings;` in MetricsServiceV2Api

**Comment by mderka** [comment]
LocalLoggingHelper and LocalLoggingImpl are missing copyright.

**Comment by mderka** [comment]
Other copyright clauses are dated 2015.

**Comment by shinfan** [comment]
PTAL

**Comment by mderka** [comment]
Checkstyle issues:

- ConfigServiceV2Api.java:65: error: Missing a Javadoc comment.
- ConfigServiceV2Api.java:181: error: Line is longer than 100 characters (found 107).
- ConfigServiceV2Api.java:192: error: Line is longer than 100 characters (found 105).
- MetricsServiceV2Settings.java:63: error: Missing a Javadoc comment.
- MetricsServiceV2Settings.java:208: error: Line is longer than 100 characters (found 107).
- LoggingServiceV2Settings.java:67: error: Missing a Javadoc comment.
- LoggingServiceV2Settings.java:222: error: Line is longer than 100 characters (found 107).
- LoggingServiceV2Settings.java:277: error: Line is longer than 100 characters (found 101).
- LoggingServiceV2Api.java:71: error: Missing a Javadoc comment.
- LoggingServiceV2Api.java:164: error: Line is longer than 100 characters (found 108).
- LoggingServiceV2Api.java:175: error: Line is longer than 100 characters (found 106).
- MetricsServiceV2Api.java:65: error: Missing a Javadoc comment.
- MetricsServiceV2Api.java:182: error: Line is longer than 100 characters (found 108).
- MetricsServiceV2Api.java:193: error: Line is longer than 100 characters (found 106).
- ConfigServiceV2Settings.java:63: error: Missing a Javadoc comment.
- ConfigServiceV2Settings.java:204: error: Line is longer than 100 characters (found 106).
- ConfigServiceV2Api.java:65: error: Missing a Javadoc comment.
- ConfigServiceV2Api.java:181: error: Line is longer than 100 characters (found 107).
- ConfigServiceV2Api.java:192: error: Line is longer than 100 characters (found 105).
- testing/LocalLoggingImpl.java:24: error: Missing a Javadoc comment.
- MetricsServiceV2Settings.java:63: error: Missing a Javadoc comment.
- MetricsServiceV2Settings.java:208: error: Line is longer than 100 characters (found 107).
- LoggingServiceV2Settings.java:67: error: Missing a Javadoc comment.
- LoggingServiceV2Settings.java:222: error: Line is longer than 100 characters (found 107).
- LoggingServiceV2Settings.java:277: error: Line is longer than 100 characters (found 101).
- LoggingServiceV2Api.java:71: error: Missing a Javadoc comment.
- LoggingServiceV2Api.java:164: error: Line is longer than 100 characters (found 108).
- LoggingServiceV2Api.java:175: error: Line is longer than 100 characters (found 106).
- MetricsServiceV2Api.java:65: error: Missing a Javadoc comment.
- MetricsServiceV2Api.java:182: error: Line is longer than 100 characters (found 108).
- MetricsServiceV2Api.java:193: error: Line is longer than 100 characters (found 106).
- ConfigServiceV2Settings.java:63: error: Missing a Javadoc comment.
- ConfigServiceV2Settings.java:204: error: Line is longer than 100 characters (found 106).
- LoggingServiceV2ApiTest.java:34: error: Missing a Javadoc comment.

**Comment by mderka** [comment]
LocalPubsubHelper creates helper on port 8080. The tests fail if this port is not free. The port should be assigned automatically.

**Comment by shinfan** [comment]
This PR is to update the generated code and the unit test. If possible, I would prefer to create a separate PR to fix the port issue.

**Comment by mderka** [comment]
Ok. Please, create an issue for this and reference it here. Also, please, fix the long lines listed above. Seems good otherwise. Let me know when you are done, I will check it again.

**Comment by shinfan** [comment]
Added the issue number to the PR description. Fixed the line length. PTAL.

**Comment by mderka** [comment]
We still have some lines that are too long and unused imports. 

```
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/ConfigServiceV2Api.java:36:8: error: Unused import: com.google.api.gax.grpc.ApiCallSettings. 
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/ConfigServiceV2Api.java:65: error: Missing a Javadoc comment.
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/ConfigServiceV2Api.java:181: error: Line is longer than 100 characters (found 107).
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/ConfigServiceV2Api.java:192: error: Line is longer than 100 characters (found 105).
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/MetricsServiceV2Settings.java:63: error: Missing a Javadoc comment.
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/MetricsServiceV2Settings.java:208: error: Line is longer than 100 characters (found 107).
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/LoggingServiceV2Settings.java:67: error: Missing a Javadoc comment.
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/LoggingServiceV2Settings.java:222: error: Line is longer than 100 characters (found 107).
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/LoggingServiceV2Settings.java:277: error: Line is longer than 100 characters (found 101).
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/LoggingServiceV2Api.java:38:8: error: Unused import: com.google.api.gax.grpc.ApiCallSettings. 
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/LoggingServiceV2Api.java:71: error: Missing a Javadoc comment.
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/LoggingServiceV2Api.java:164: error: Line is longer than 100 characters (found 108).
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/LoggingServiceV2Api.java:175: error: Line is longer than 100 characters (found 106).
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/MetricsServiceV2Api.java:36:8: error: Unused import: com.google.api.gax.grpc.ApiCallSettings. 
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/MetricsServiceV2Api.java:65: error: Missing a Javadoc comment.
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/MetricsServiceV2Api.java:182: error: Line is longer than 100 characters (found 108).
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/MetricsServiceV2Api.java:193: error: Line is longer than 100 characters (found 106).
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/ConfigServiceV2Settings.java:63: error: Missing a Javadoc comment.
./baseline/src/main/java/com/google/gcloud/logging/spi/v2/ConfigServiceV2Settings.java:204: error: Line is longer than 100 characters (found 106).
./src/main/java/com/google/gcloud/logging/spi/v2/ConfigServiceV2Api.java:66: error: Missing a Javadoc comment.
./src/main/java/com/google/gcloud/logging/spi/v2/testing/LocalLoggingImpl.java:38: error: Missing a Javadoc comment.
./src/main/java/com/google/gcloud/logging/spi/v2/MetricsServiceV2Settings.java:64: error: Missing a Javadoc comment.
./src/main/java/com/google/gcloud/logging/spi/v2/LoggingServiceV2Settings.java:68: error: Missing a Javadoc comment.
./src/main/java/com/google/gcloud/logging/spi/v2/LoggingServiceV2Api.java:72: error: Missing a Javadoc comment.
./src/main/java/com/google/gcloud/logging/spi/v2/MetricsServiceV2Api.java:66: error: Missing a Javadoc comment.
./src/main/java/com/google/gcloud/logging/spi/v2/ConfigServiceV2Settings.java:64: error: Missing a Javadoc comment.
./src/test/java/com/google/gcloud/logging/spi/v2/LoggingServiceV2ApiTest.java:34: error: Missing a Javadoc comment.
```

**Comment by shinfan** [comment]
PTAL

**Comment by mderka** [comment]
Ok, that is gone. As far as the codacy report goes, are you able to address the "Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes." errors?

**Comment by shinfan** [comment]
Added https://github.com/GoogleCloudPlatform/gcloud-java/issues/771 to description

**Comment by mderka** [comment]
Perfect. LGTM

**Pull request merged**
