### PR TITLE
chore: merge java-core, java-shared-dependencies, and java-iam into google-cloud-java

### PR DESCRIPTION
**Pull request by suztomo**
Message to me: Use MERGE commit so that the commit history is preserved.

# How I created this pull request

```
sh generation/merge_repository.sh
cd generation/monorepo/google-cloud-java-merged
git checkout -b merge_repos
git rm -r java-core/.OwlBot.yaml {java-core,java-iam,java-shared-dependencies}/{.github,.kokoro,CODE_OF_CONDUCT.md,CONTRIBUTING.md,LICENSE,SECURITY.md,codecov.yaml,java.header,renovate.json,versions.txt,.gitignore}
 # Remove repo-metadata in java-shared-dependencies so that the generation script does
 # not recognize this module as a client library
 git rm java-shared-dependencies/.repo-metadata.json
```

Manually modify parent poms:

- java-core: google-cloud-jar-parent
- java-shared-dependencies: google-cloud-pom-parent
- java-iam: google-cloud-jar-parent

Manually modify java-core so that it inherits google-cloud-jar-parent and no need to set versions listed in the shared dependencies BOM.

Manually modify check_non_release_please_versions.sh to adjust java-shared-dependencies are ok to declare versions.

Manually modify google-cloud-jar-parent/pom.xml so that it uses the shared dependencies BOM within this repository.

Ran `bash generation/consolidate_config.sh` to remove unnecessary XML elements.

Manually remove "distributionManagement" section in the newly added modules.

Manually removed .OwlBot.yaml from java-core and java-shared-dependencies because they are not generated libraries. Applied generation/set_owlbot_config.sh to update java-iam/.OwlBot.yaml.

Ran:

```
git rm java-iam/license-checks.xml java-core/license-checks.xml java-shared-dependencies/license-checks.xml
git rm java-shared-dependencies/owlbot.py java-core/owlbot.py
```

Ran `generation/update_owlbot_postprocessor_config.sh` to update java-iam/owlbot.py.

Manually modified generation/set_parent_pom.sh to exclude java-shared-dependencies; otherwise java-shared-dependencies would set parent as google-cloud-jar-parent, which depends on java-shared-dependencies (circular dependency and build failure).

### CODE REVIEW

**Review by meltsufin — COMMENTED** [review]
Can you please provide the commands used to create this branch?

**Comment by suztomo** [comment]
@meltsufin I started adding the changes I need there in pull request description.

**Comment by suztomo** [comment]
Todo: the new client generation fails. Luckily it creates a branch newclient_output_pull_request for troubleshooting:

```
suztomo@suztomo:~/google-cloud-java$ git checkout -b newclient_output_pull_request_investigation origin/newclient_output_pull_request
suztomo@suztomo:~/google-cloud-java$ mvn validate
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] The dependencies of type=pom and with scope=import form a cycle: com.google.cloud:google-cloud-shared-dependencies:3.1.3-SNAPSHOT -> com.google.cloud:google-cloud-shared-dependencies:3.1.3-SNAPSHOT @ com.google.cloud:google-cloud-shared-dependencies:3.1.3-SNAPSHOT
...
```

`[ERROR] The dependencies of type=pom and with scope=import form a cycle: com.google.cloud:google-cloud-shared-dependencies:3.1.3-SNAPSHOT -> com.google.cloud:google-cloud-shared-dependencies:3.1.3-SNAPSHOT @ com.google.cloud:google-cloud-shared-dependencies:3.1.3-SNAPSHOT`.

**Comment by suztomo** [comment]
Now checks are green. (CLA bot doesn't work with that number of commits. But we know these commits come from repositories that had CLA bot.)

Memo to myself: Do not squash. Merge.

**Pull request merged**
