### PR TITLE
Update Video Intelligence release level to Beta

### PR DESCRIPTION
**Pull request by danoscarmike**

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Updating the README isn't sufficient to bump Video Intelligence to Beta - we'll need to update the pom files too.

**Comment by neozwu** [comment]
I took the liberty and pushed another commit with pom changes.  @garrettjonesgoogle @vam-google , PTAL.

**Comment by neozwu** [comment]
Ping @vam-google @garrettjonesgoogle

**Comment by garrettjonesgoogle** [comment]
LGTM

**Pull request merged**
