### PR TITLE
BigQuery: Adding support for schema autodetection

### PR DESCRIPTION
**Pull request by gene-telligent**
This has been exposed through the protobuf API already; I just coded in a method to access it through the Java SDK.

See: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load.autodetect

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
@tswast could you take a look?

**Comment by garrettjonesgoogle** [comment]
@tswast I don't think we've been putting annotations on methods to match the support level of the underlying API. It gets tricky when the support level of the underlying API changes, because then we might have to keep revising the annotations in the client library to match. 

The tag we have been using for features that might change in the client library is `@ExperimentalApi` (defined in protobuf).

**Comment by gene-telligent** [comment]
Hi all,

I've rebased the commit with the latest from master (waiting on CI builds to complete now, but internal running of the tests raised no errors). 

I didn't use `@ExperimentalApi` as it seems to be an annotation reserved for the SPI libraries.

**Comment by tswast** [comment]
@garrettjonesgoogle could you merge? I haven't been tracking when releases are happening. I don't want to step on the release process again.

**Pull request merged**
